### PR TITLE
Generalized add_stat() for more complex returns

### LINKED ISSUE #746: Create an add_stats() function to allow function returning multiple statistics for each variable/categorical level
**Behavior expected**
For now, `add_stat()` accepts a function parameter that must return a vector, containing a unique statistic for each variable and/or each categorical level of a summary.

Since many statistical functions generate multiple statistics at once (ie: size effect, residuals, p-values), it could be useful to allow a function parameter to return a dataframe instead of a vector (columns would be for statistics and rows for variables).

**Current workaround**:
One way to do it is to call multiple times `add_stat()` with slightly different function to return a different statistic, but it can be very costly since it runs multiple times the same statistical test on the same data:

``` r
library(gtsummary)

# fn returns t-test t-statistic ONLY
my_ttest_t <- function(data, variable, by, ...) {
  t.test(data[[variable]] ~ as.factor(data[[by]]))$statistic
}

# fn returns t-test p-value ONLY
my_ttest_p <- function(data, variable, by, ...) {
  t.test(data[[variable]] ~ as.factor(data[[by]]))$p.value
}

add_stat_ex1 <- trial %>%
  select(trt, age, marker) %>%
  tbl_summary(by = trt, missing = "no") %>%
  # Adding t-statistics and p-values from t.test
  add_stat(
    fns = everything() ~ my_ttest_t,  # all variables compared with with t-test
    header = "**t (Student)**"
  ) %>% 
  add_stat(
    fns = everything() ~ my_ttest_p,  # all variables compared with with t-test (AGAIN)
    header = "**P-value**",
    fmt_fun = style_pvalue            # format p-values with style_pvalue()
  )
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Solution proposed**
I propose to create an `add_stats()` function (note the plural form) that would allow returning multiple statistics for each variable/categorical level like this:

``` r
library(gtsummary)

# fn returns t-test t-statistic AND pvalue
my_ttest <- function(data, variable, by, ...) {
  result <- t.test(data[[variable]] ~ as.factor(data[[by]]))
  
  list(
    t = result$statistic,
    p.value = result$p.value
  )
}

add_stat_ex1 <- trial %>%
  select(trt, age, marker) %>%
  tbl_summary(by = trt, missing = "no") %>%
  # Adding t-statistics and p-values from t.test
  add_stats(
    fns = everything() ~ my_ttest,  # all variables compared with with t-test
    fmt_fun = list(
        t = NULL,                   # no styling for t-statistics
        p.value = style_pvalue,     # format p-values with style_pvalue()
      ),
    header = list(                  # new column headers
      t = "**t (Student)**",
      t = "**P-value**"
    )
  )
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* The `add_stat()` function may now return multiple columns of new statistics. (#746)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #746 

```r
my_ttest <- function(data, variable, by, ...) {
  t.test(data[[variable]] ~ factor(data[[by]])) %>%
    broom::tidy() %>%
    select(estimate, conf.low, conf.high, p.value)
}

trial %>%
  select(trt, age, marker) %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_stat(
    fns = everything() ~ my_ttest
  )
```
image

To do...
- [x] Update documentation
- [x] Test fn on categorical levels
- [x] Add more unit tests

cc @JeremyPasco FYI

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by JeremyPasco** [comment]
Thanks a lot!
How should categorical level stats be returned ? I've tried with a tibble with rows in the factors order but no success.
``` r
remotes::install_github("ddsjoberg/gtsummary", ref="add_stats_update")
#> Skipping install of 'gtsummary' from a github remote, the SHA1 (6f04a0cd) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(gtsummary)
library(tidyverse)

my_test <- function(data, variable, by, ...) {
  tibble(stat_x = 1:4, stat_y=7:10)
}

trial %>%
  # select(trt, age, marker) %>%
  select(trt, stage) %>% 
  tbl_summary(by = trt, missing = "no") %>%
  add_stat(
    fns = everything() ~ my_test
  )
#> Error: Dimension of 'stage' and the added statistic do not match. Expecting statistic/data frame to be length/no. rows 1.
```

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JeremyPasco** [comment]
Returning global statistics for a categorical variable does work:

``` r
remotes::install_github("ddsjoberg/gtsummary", ref="add_stats_update")
library(gtsummary)
library(tidyverse)

my_test <- function(data, variable, by, ...) {
  tibble(
    stat_x = 10, stat_y=20
  )
}

trial %>%
  select(trt, stage) %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_stat(
    fns = everything() ~ my_test,
    header = c(
      '**X**','**Y**'
    )
  )
```



<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ulvgzlnpha .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ulvgzlnpha .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ulvgzlnpha .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ulvgzlnpha .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ulvgzlnpha .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ulvgzlnpha .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ulvgzlnpha .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ulvgzlnpha .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ulvgzlnpha .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ulvgzlnpha .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ulvgzlnpha .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ulvgzlnpha .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ulvgzlnpha .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ulvgzlnpha .gt_from_md > :first-child {
  margin-top: 0;
}

#ulvgzlnpha .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ulvgzlnpha .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ulvgzlnpha .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ulvgzlnpha .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ulvgzlnpha .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ulvgzlnpha .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ulvgzlnpha .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ulvgzlnpha .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ulvgzlnpha .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ulvgzlnpha .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ulvgzlnpha .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ulvgzlnpha .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ulvgzlnpha .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ulvgzlnpha .gt_left {
  text-align: left;
}

#ulvgzlnpha .gt_center {
  text-align: center;
}

#ulvgzlnpha .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ulvgzlnpha .gt_font_normal {
  font-weight: normal;
}

#ulvgzlnpha .gt_font_bold {
  font-weight: bold;
}

#ulvgzlnpha .gt_font_italic {
  font-style: italic;
}

#ulvgzlnpha .gt_super {
  font-size: 65%;
}

#ulvgzlnpha .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="ulvgzlnpha" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug A</strong>, N = 98<sup class="gt_footnote_marks">1</sup>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug B</strong>, N = 102<sup class="gt_footnote_marks">1</sup>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>X</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Y</strong>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

T Stage

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

10

</td>

<td class="gt_row gt_center">

20

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

T1

</td>

<td class="gt_row gt_center">

28 (29%)

</td>

<td class="gt_row gt_center">

25 (25%)

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

T2

</td>

<td class="gt_row gt_center">

25 (26%)

</td>

<td class="gt_row gt_center">

29 (28%)

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

T3

</td>

<td class="gt_row gt_center">

22 (22%)

</td>

<td class="gt_row gt_center">

21 (21%)

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

T4

</td>

<td class="gt_row gt_center">

23 (23%)

</td>

<td class="gt_row gt_center">

27 (26%)

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

</tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="5">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

n (%)
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>



<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
@JeremyPasco I'm not at a computer to test the code, but you do need to add the location argument to indicate where the statistics are meant to be placed

**Comment by JeremyPasco** [comment]
Nice! Adding `location = "level"` did the job, thanks:
``` r
remotes::install_github("ddsjoberg/gtsummary", ref="add_stats_update")
library(gtsummary)
library(tidyverse)

my_test <- function(data, variable, by, ...) {
  tibble(
    stat_x = 1:4, stat_y=7:10
  )
}

trial %>%
  select(trt, stage) %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_stat(
    fns = everything() ~ my_test,
    header = c(
      '**X**','**Y**'
    ),
    location = "level"
  )
```

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
@JeremyPasco if you have ideas how to improve documentation to make usage more clear, happy to hear it 🐙

**Comment by JeremyPasco** [comment]
I can provide more examples based on these new features if it's ok for you. But first I'd like to test deeplier the genericity of the current API.

One case makes me wondering if the location parameter could be improved:
I usually have many categorical variables that must be handled differently in the same table. One could be ordinal, meaning that each factor would be compared with the reference one, so `location="level"`. Others could be multinomial, implying a unique result with `location="label"`.

`add_stat` allows me to specify different test functions to solve that, but `location` allows only one value between label and level.

A workaraound could be to chain add_stat but it feels redondant (and fails):
``` r
remotes::install_github("ddsjoberg/gtsummary", ref="add_stats_update")
library(gtsummary)
library(tidyverse)

test_each_level <- function(data, variable, by, ...) {
  tibble(
    stat_x = 1:4, stat_y= 5:8
  )
}

global_test <- function(data, variable, by, ...) {
  tibble(
    stat_x = 50, stat_y= 60
  )
}

trial %>%
  select(trt, stage, grade) %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_stat(
    fns = list(stage ~ test_each_level),
    header = c('**X**','**Y**'),
    location = "level"
  ) %>%
  add_stat(
    fns = list(grade ~ global_test),
    header = c('**X**','**Y**'),
    location = "label"
  )
#> Error: New added columns 'stat_x', 'stat_y' already exist in `x$table_body`.
```
<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Wouldn't the following approach make more sense? (allowing a list in location parameter)
``` r
remotes::install_github("ddsjoberg/gtsummary", ref="add_stats_update")
library(gtsummary)
library(tidyverse)

test_each_level <- function(data, variable, by, ...) {
  tibble(
    stat_x = 1:4, stat_y= 5:8
  )
}

global_test <- function(data, variable, by, ...) {
  tibble(
    stat_x = 50, stat_y= 60
  )
}

trial %>%
  select(trt, stage, grade) %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_stat(
    fns = list(
      stage ~ test_each_level,
      grade ~ global_test
    ),
    header = c('**X**','**Y**'),
    location = list(
      stage ~ "level",
      grade ~ "label"
    )
  )
#> Error in match.arg(location): 'arg' doit être NULL ou une chaîne de caractères
```

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JeremyPasco** [comment]
Here is another case I'm working with: if add_stat add specific statistics for categorical and continuous variables, there are few issues:
- ordre of added statistic columns is "hardly" predictable (depending on the order of statistics in fns parameter), 
- this order can't be customized (but I may have missed something here?)
- then, specifying custom headers for these columns seems hazardous since the header parameter allocates header labels based on their vector position

``` r
library(gtsummary)
library(tidyverse)

my_student <- function(data, variable, by, ...){
  result <- t.test(data[[variable]] ~ as.factor(data[[by]]))
  tibble(
    mean_diff = paste0(
      style_sigfig(result$estimate[2]-result$estimate[1]),
      ' [', style_sigfig(result$conf.int[1]), ' ; ',
      style_sigfig(result$conf.int[2]), ']'
    ),
    p.value = style_pvalue(result$p.value, prepend_p = TRUE)
  )
}

my_fisher <- function(data, variable, by, ...){
  result <- fisher.test(table(data[[variable]], data[[by]]))
  tibble(
    or = paste0(
      style_sigfig(result$estimate),
      ' [', style_sigfig(result$conf.int[1]), ' ; ',
      style_sigfig(result$conf.int[2]), ']'
    ),
    p.value = style_pvalue(result$p.value, prepend_p = TRUE)
  )
}

trial %>% 
  select(trt, stage, age) %>% 
  mutate(stage = stage == "T1") %>% 
  tbl_summary(
    by = trt
  ) %>% 
  add_stat(
    fns = list(
      all_continuous() ~ my_student,
      all_categorical() ~ my_fisher
    )
  )
```

<sup>Created on 2021-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This reprex adds 3 columns in the following order : `mean_diff`, `p.value` and `or`. If I switch fns tests order, I get the reverse column order : `or`, `p.value` and `mean_diff`. Therefore, headers can't be linked easily to specific columns.

What do you think of the following proposal?
- allowing a list of formulas in header parameter like this (not relying on column order anymore):
  ```r
  header = list(
     mean_diff ~ '**Mean difference**',
     or ~ '**Odd ratio**',
     p.value ~ '**P value**',
  )
  ```
- bonus: the order of header formulas would be used to reorder generated columns!

**Comment by ddsjoberg** [comment]
@JeremyPasco thank you for the input!

I don't know if I agree that the ordering of the new columns in unpredictable...it's the same order if you stack data frames, and the user is specifying the order of the columns in the fns- arg. But I certainly do take your point that it is not the easiest specification for header, footnote, and formatting functions.

I am somewhat inclined to remove these arguments all together, i.e. `add_stat(fmt_fun=, header=, footnote=)`, and require users to utilize `modify_header()`, `modify_footnote()`.  I would then add a `modify_fmt_fun()`. Ultimately these more general functions have a better API for specifying these table attributes.  

FYI, in the next release, I am making footnotes and formatting functions more general allowing row and column specifications. This means that specifications in `add_stat(fmt_fun=, header=, footnote=)` would need to be even more complicated to accommodate the row and column specifications.

**Comment by JeremyPasco** [comment]
Thanks for leading me to modify_xxx functions, it seems indeed a nicer way to handle all use cases. 
That solves the column order for setting headers. Just wondering how to reorder added columns, is there a function that can do it? Specifying the order in fns parameter is not enough in my previous reprex:
```r
fns = list(
      all_continuous() ~ my_student,
      all_categorical() ~ my_fisher
    )
```
Will give this order: `mean_diff`, `p.value` and `or`

```r
fns = list(
      all_categorical() ~ my_fisher,
      all_continuous() ~ my_student
    )
```
Will give this order: `or`, `p.value` and `mean_diff`

But I was looking for a third solution: `or`, `mean_diff` and `p.value`

**Comment by ddsjoberg** [comment]
@JeremyPasco you can reorder the columns using `modify_table_body(x, fun = dplyr::relocate, diff, .after = or)`

**Comment by ddsjoberg** [comment]
OK!  I think this PR is good to go except it must be merged AFTER https://github.com/ddsjoberg/gtsummary/pull/738 .

In the meantime, I can add a few more unit tests, and perhaps an example to the gallery.

**Comment by ddsjoberg** [comment]
Hey hey @JeremyPasco !

This pull request was waiting on another that is now merged.  This pull request is ready for final review. If you have a moment, can you review the documentation and the function. I think it does everything we need. Thank you for taking the time to comment previously and making the final function much better.

**Comment by JeremyPasco** [comment]
@ddsjoberg Nice! Thanks a lot. I start my explorations right now :)

**Comment by JeremyPasco** [comment]
Wow it works like a charm! This method is really a game changer to me. Its genericity and the package globally exceed by far all the stacks I've been exploring the last few years. It even feels faster in this last version when processing 50+ variables (but I didn't benchmark it before so not sure).

Exposing the tbl parameter in stat functions helped me simplifying a lot of situations (ie: finding which value was displayed in dichotomous variables to adapt returned statistics).

The documentation is perfectly clear to me.

THANKS A LOT!

I'm planning to use this intensely the next few months. I'll give you a feedback then, and probably some in-depth examples you could use in the Table Gallery if you're interested in.

**Comment by JeremyPasco** [comment]
Maybe just one tip to put in documentation: if a stat function returns a p.value, it should be raw and put in a `p.value` column to take advantage of the global p-value style put in the theme (prepend_p, decimal.separator, digits, bold_p...).

**Comment by ddsjoberg** [comment]
> Maybe just one tip to put in documentation: if a stat function returns a p.value, it should be raw and put in a `p.value` column to take advantage of the global p-value style put in the theme (prepend_p, decimal.separator, digits, bold_p...).

that is a good point. Added!

**Pull request merged**
