### PR TITLE
Selecting function updates

### LINKED ISSUE #648: Clean up the tidyselect functions
I understand rlang, environments, and tidyselect much better than I did when I wrote `tidyselect_to_list()`, `var_input_to_string()`, and `tidyselect_to_string()`

1. Should this re-write only occur after the `vars()` notation is fully deprecated? This could take a year or more.
1. Remember that `vars()` is the same as `quos()`. If the `vars()` fn is detected, all we likely need to do is bang-bang it, e.g. `!!vars(...)`

### LINKED ISSUE #677: tbl_regression() takes three lines for categorical variables
When using tbl_regression() to create a lme4::lmer() or lme4::glmer() table with categorical variables, there are three lines in the table for each variable. I would expect each variable to use a single line by default, or alternatively, a parameter to be able to get a more compact table (`compact = TRUE`)?

Slightly different things happen depending on the type of coding used (contrast coding or dummy coding: http://www.lrdc.pitt.edu/maplelab/slides/Simple_Main_Effects_Fraundorf.pdf)

Here the rds files with the models: [models_PPV.zip](https://github.com/ddsjoberg/gtsummary/files/5338816/models_PPV.zip)

## Contrast coding

In the example below, you can see we have the **brochure** IV with two levels (standard and pictorial), and gtsummary takes three lines, but just with the one in the middle would be enough `brochure (standard - pictorial)`, given it includes all the necessary information.

``` r

library(gtsummary)
library(lme4)

  
model_PPV = readRDS("model_PPV_contrast.rds")
gtsummary::tbl_regression(model_PPV, exponentiate = FALSE)

```

<div id="gtjsiblllv" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Beta</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

brochure

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

brochure (standard - pictorial)

</td>

<td class="gt_row gt_center">

7.7

</td>

<td class="gt_row gt_center">

4.0, 11

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

pictorial

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

normative PPV

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

normative PPV (high - low)

</td>

<td class="gt_row gt_center">

\-23

</td>

<td class="gt_row gt_center">

\-25, -20

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

low

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

medical condition

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

medical condition (Breast cancer - Down syndrome)

</td>

<td class="gt_row gt_center">

1.0

</td>

<td class="gt_row gt_center">

\-1.4, 3.5

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Down syndrome

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

item

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

item (2 - 1)

</td>

<td class="gt_row gt_center">

3.1

</td>

<td class="gt_row gt_center">

0.65, 5.6

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

1

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

a priori

</td>

<td class="gt_row gt_center">

0.05

</td>

<td class="gt_row gt_center">

\-0.10, 0.20

</td>

</tr>

<tr>

<td class="gt_row gt_left">

agreeableness

</td>

<td class="gt_row gt_center">

\-0.20

</td>

<td class="gt_row gt_center">

\-5.1, 4.7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

brochure \* normative PPV

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

brochure (standard - pictorial) \* normative PPV (high - low)

</td>

<td class="gt_row gt_center">

\-10

</td>

<td class="gt_row gt_center">

\-13, -8.0

</td>

</tr>

</tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="3">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

CI = Confidence Interval
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

## Dummy coding for _brochure_

Something similar happening here. Other packages (e.g. sjplot) would show a single line: `brochure [pictorial]`	

``` r
  
library(gtsummary)
library(lme4)

  
model_PPV = readRDS("model_PPV_dummy.rds")
gtsummary::tbl_regression(model_PPV, exponentiate = FALSE)

```

<div id="cpzdleujet" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Beta</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

brochure

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

standard

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

pictorial

</td>

<td class="gt_row gt_center">

\-15

</td>

<td class="gt_row gt_center">

\-23, -8.1

</td>

</tr>

<tr>

<td class="gt_row gt_left">

normative PPV

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

normative PPV (high - low)

</td>

<td class="gt_row gt_center">

\-33

</td>

<td class="gt_row gt_center">

\-37, -30

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

low

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

medical condition

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

medical condition (Breast cancer - Down syndrome)

</td>

<td class="gt_row gt_center">

1.0

</td>

<td class="gt_row gt_center">

\-1.4, 3.5

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Down syndrome

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

item

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

item (2 - 1)

</td>

<td class="gt_row gt_center">

3.1

</td>

<td class="gt_row gt_center">

0.65, 5.6

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

1

</td>

<td class="gt_row gt_center">

—

</td>

<td class="gt_row gt_center">

—

</td>

</tr>

<tr>

<td class="gt_row gt_left">

a priori

</td>

<td class="gt_row gt_center">

0.05

</td>

<td class="gt_row gt_center">

\-0.10, 0.20

</td>

</tr>

<tr>

<td class="gt_row gt_left">

agreeableness

</td>

<td class="gt_row gt_center">

\-0.20

</td>

<td class="gt_row gt_center">

\-5.1, 4.7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

brochure \* normative PPV

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

pictorial \* normative PPV (high - low)

</td>

<td class="gt_row gt_center">

21

</td>

<td class="gt_row gt_center">

16, 26

</td>

</tr>

</tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="3">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

CI = Confidence Interval
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### LINKED ISSUE #680: Update `.$table_body` to work with the `all_*()` select helpers from {broom.helpers}
The broom.helpers package now has selectors `all_continuous()`, `all_categorical()`, `all_dichotomous()`, and `all_interaction()`. Can I update the internals of `.$table_body` to use the broom.helpers versions?
https://github.com/larmarange/broom.helpers/pull/55

There is an issue that `tbl_summary()` and `tbl_svysummary()` has `"continuous2"` types.  The `gtsummary::all_continuous()` defaults to selecting `"continuous2"` and includes the option to select `"continuous"` only.  There is also a `gtsummary::all_continuous2()` function.

### LINKED ISSUE #692: Calling `tidy_plus_plus()` arguments for `tbl_regression()`?
What is the best way allow users to pass additional arguments to `tidy_plus_plus()` for further customization?
Things I value in the solution (which does not need to implemented in the next release):
  - functions with few arguments
  - the majority of users have a good experience with the function and are not overwhelmed with too much information when encountering the function.
  - tables are highly customizable

1. Allow users to set default values for `tidy_plus_plus()` via gtsummary theme elements.
    - Pros
      - Easily implemented
      - Can make `theme_gtsummary_plus_plus(<list each additional arg to modify>)` to easily modify `tidy_plus_plus()` arguments
      - Does not overburden new/majority of users who may not need this type of feature
      - This can be implemented now, while we decide on whether to implement other options
    - Cons
      - Writing/Saving gtsummary themes is not easy. Although, users can use an exported theme. 
      - Not easily discoverable by the advanced users
1. Add a `tbl_regression(tidy_plus_plus=list(additional arg))` argument.
    - Pros
      - Will be visible to users, so advanced users can discover the option
    - Cons
      - I don't like adding more args to the function, especially for args most users may not use? But this is only one arg....

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- All select helper functions and the utility functions that make them possible, have been cleaned up and migrated to broom.helpers.  THIS IS A HUGE UPDATE.
- Migrated all selecting functionality from gtsummary to broom.helpers.  Exporting functions the functions below.  Each has been improved and streamlined compared to their original versions in gtsummary.
    - `.generic_selector()`: this is a function that makes it easy to create selecting functions like `all_continuous()`.  The internals allow for it to be used in broom.helpers and gtsummary seamlessly. 
    - `.select_to_varnames()`: This function converts selecting syntax into character varnames
    - `.formula_list_to_named_list()`: this function takes the formula selecting syntax used widely in gtsummary, and converts it to a named list. 
- Update to use `broom.helpers::tidy_plus_plus()` instead of the individual `broom.helpers::tidy_*()` functions. 
- Theme element has been added for controlling the other `tidy_plus_plus()` arguments.
- `tbl_regression(add_estimate_to_reference_rows=)` argument has been added. Added to `tbl_uvregression()` as well.
- Theme element for `tbl_regression(add_estimate_to_reference_rows=)` has been added.
- The argument `all_continuous(continuous2=)` has been removed.  No deprecation messages were added...it was just cut.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #648 
closes #680
closes #692 
closes #677

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN=true)` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@karissawhiting @michaelcurry1123 helllllooo!  I miss you guys!

Can either of you or both of you review this PR?

**Comment by ddsjoberg** [comment]
@karissawhiting @michaelcurry1123

To prepare the `tbl_regression()` `.$table_body` we are now using `broom.helpers::tidy_plus_plus()` https://larmarange.github.io/broom.helpers/reference/tidy_plus_plus.html
It has all the functionality of to prepare the table body we had already implemented plus other options.  All the arguments in `tidy_plus_plus()` not already utilized in `tbl_regression()` can by modified with theme elements. But what do you think of adding some/all of these options as arguments to `tbl_regression()`.

1. I think the most widely used arg may be `add_estimate_to_reference_rows=`, which will add a 0 (or 1 of exponentiated) to the reference row (we currently show an emdash). We could add just this one argument.

1. We could add an argument like `tbl_regression(tidy_plus_plus = list(add_estimate_to_reference_rows = TRUE, other.arg = FALSE))`, where users could pass a list of arguments that will then be passed to `tidy_plus_plus()`.

1. We could add both `tbl_regression(add_estimate_to_reference_rows=, tidy_plus_plus=)`?

1. We could add none of them, and keep control of these elements via themes only.

What do you think? ❤️

**Comment by larmarange** [comment]
From my point of view, I would prefer solution 1 or 3.

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I would agree with the above, I think 1 and/or 3 would be ideal.

**Comment by ddsjoberg** [comment]
Thanks @larmarange @michaelcurry1123 , i'll implement number 1 for now, and if we choose we can always add  number 3 before the release, or whenever

**Comment by michaelcurry1123** [comment]
@ddsjoberg should I update the branch?

**Comment by ddsjoberg** [comment]
Update with corrections? Sure!

**Comment by ddsjoberg** [comment]
Ohh updating from master 👍👍👍

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I think you had to review, apologize if you did not want the update from master

**Comment by ddsjoberg** [comment]
Oh updating was def the thing to do @michaelcurry1123

**Comment by michaelcurry1123** [comment]
There is some masking issues with the migration of the select helpers to broom.helpers
The first example below will show the iqr and range. If you load broom.helpers after gtsummary the helper functions are masked and it does not display the other metric (range). The third example is a work around but not sure if you want that to be the way this selectors work.  @ddsjoberg 

```
library(gtsummary)

#this table will give you the median iqr and range

tbl_summary(select(trial,age,trt),
            by = trt,
            type = all_continuous() ~ "continuous2",
            statistic = all_continuous() ~ c(
                          "{median} ({p25}, {p75})", 
                          "{min}, {max}" ))

#restart r here

library(gtsummary)
library(tidyverse)
library(broom.helpers)

#no range is displayed
tbl_summary(select(trial,age,trt),
            by = trt,
            type = all_continuous() ~ "continuous2",
            statistic = all_continuous() ~ c(
              "{median} ({p25}, {p75})", 
              "{min}, {max}" ))


tbl_summary(select(trial,age,trt),
            by = trt,
            type = gtsummary::all_continuous() ~ "continuous2",
            statistic = gtsummary::all_continuous() ~ c(
              "{median} ({p25}, {p75})", 
              "{min}, {max}" ))

```

**Comment by ddsjoberg** [comment]
@michaelcurry1123 ! thanks!

this issue comes up because both gtsummary and broom.helpers export a `all_continuous()` function and they are slightly different.  The gtsummary version captures both `"continuous"` and `"continuous2"` summary types.  The `"continuous2"` type does not exist in broom.helpers and `broom.helpers::all_continuous()` only captures type `"continuous"`.

There are a couple of ways we could tackle this:
1. Do nothing, and assume that most users won't be using both gtsummary and broom.helpers at the same time.

1. The `gtsummary::all_continuous(continuous2 = TRUE)` has an argument that selects `continuous2` types.  We could make an update to `broom.helpers::all_continuous()` to select all types that start with `"continuous"`, thus selecting both continuous types. We could then import `broom.helpers::all_continuous()` into gtsummary as is with no masking conflict.  This would be a breaking change for `gtsummary::all_continuous()` because users would no longer be able to select type continuous, excluding type continuous2 (but I don't think anyone is really doing that). If we make this change, every `all_*()` function in broom.helpers and gtsummary would be identical and they could all be imported from broom.helpers. @larmarange would this update work for you on the broom.helpers side?

**Comment by larmarange** [comment]
> 2\. @larmarange would this update work for you on the broom.helpers side?

Not a problem on my side. We cant update `broom.helpers` accordingly

**Comment by michaelcurry1123** [comment]
Would it be safe to assume people would not use these packages at the same time?  @larmarange  did you mean you could update or cannot update? In your above response it says can't and not can

**Comment by larmarange** [comment]
Sorry. Can.

**Comment by ddsjoberg** [comment]
Thanks @michaelcurry1123 and @larmarange for the input

1. I updated `broom.helpers::all_continuous()` to select all types that begin with `"continuous"`; therefore, selecting `"continuous2"` as well. This is a breaking change for `gtsummary::all_continuous(continuous2 = TRUE)` as there is no more function argument. Pending PR https://github.com/larmarange/broom.helpers/pull/75

1. All the select helpers in broom.helpers are now imported and re-exported by gtsummary (no more name conflicts).

1. An unrelated change made is that the `all_factor()`, `all_character()` family of functions are warn deprecated instead of defunct, making them still usable until their final deprecation.

**Comment by ddsjoberg** [comment]
Hello @michaelcurry1123 !  Just wanted to confirm whether this review is done? 🍁

**Review by michaelcurry1123 — APPROVED** [review]

**Pull request merged**
