### PR TITLE
themes api update

### LINKED ISSUE #522: theme usage API change?
After using the themes for a bit, I am feeling that code is unnecessarily cumbersome.
```r
set_gtsummary_theme(theme_gtsummary_journal("jama"))
```

It would be easier to read, and faster to type if the code were merely
```r
theme_gtsummary_journal("jama")
```

We would still maintain the `set_gtsummary_theme()` function so users can implement their own themes, but it won't be required for internally saved themes.

If we update the internal theme functions to invisibly return the list of theme elements this will not be a breaking change.  Just putting the idea out there. Need to think about it a bit more.

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- Users no longer need call `set_gtsummary_theme(theme_gtsummary_journal())`.  They can just call `theme_gtsummary_journal()`.
- Each built-in theme now has an argument `set_theme = TRUE`. When FALSE, the theme function will invisibly return the named list the theme elements, and the theme will not be set.
- Some theme-related documentation updates

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #522 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch 
- [ ] NEWS.md has been updated under the heading "`# gtsummary (development version)`"?
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] If a new function was added, function included in `pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by michaelcurry1123** [comment]
This is great! The only question I had was:

- should huxtable also be listed as a printing engine option for this function `theme_gtsummary_printer()`?

**Comment by ddsjoberg** [comment]
@michaelcurry1123 thanks for reviewing!!

Regarding huxtable, we've delayed support for huxtable until the next release.  During our last release, they were also making a major release that had some breaking changes. So we opted to just delay one release cycle instead of putting something out that would immediately break with their release.

**Comment by michaelcurry1123** [comment]
I approved and you have to merge correct? @ddsjoberg

**Comment by ddsjoberg** [comment]
YAY! @michaelcurry1123 

If you'd like me to go through the final checklist above and merge, I can.  You are also more than welcome to do so. Let me know.

**Comment by michaelcurry1123** [comment]
@ddsjoberg ok great, I merged! but you can delete the branch :) I am scared

**Comment by ddsjoberg** [comment]
@michaelcurry1123 i am going to revert the pull request, and increase the version number, etc, then merge

**Comment by ddsjoberg** [comment]
oh nevermind, that'll just complicate things lol.  it doesn't really matter that much if the dev version number is incremented every time 🤷

**Pull request merged**
