### PR TITLE
fixes missing pvalues not showing for variables containing spaces

### LINKED ISSUE #682: missing p-values in variables containing spaces
If a variable has spaces (e.g. `normative PPV`), add_global_p() would not show the p value.

I added a quick Pull request (https://github.com/ddsjoberg/gtsummary/pull/683) replacing the back ticks from the variables in the car_Anova df before the `filter(.data$variable %in% !!include)`, so the names will match.

Please, feel free to ignore my pull request for a more elegant soluction :)

``` r

# Libraries ---------------------------------------------------------------

library(readr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(here)
#> here() starts at /home/emrys/gorkang@gmail.com/RESEARCH/PROYECTOS/2018-Imke/DATA_ANALYSIS/JDM_brochures
library(gtsummary)
library(lme4)
#> Loading required package: Matrix

theme_gtsummary_compact()
#> Setting `Compact` theme




# Read and prepare data ---------------------------------------------------

DF = read_rds("/home/emrys/gorkang@gmail.com/RESEARCH/PROYECTOS/2018-Imke/DATA_ANALYSIS/JDM_brochures/dev/BUG/gtsummary/df_JOINED2.rds")

DF_renamed = 
  DF %>% 
  rename(`normative PPV` = normative_PPV,
         `a priori` = ind_apriori)

mod_contrast = lme4::lmer(error_PPV ~ brochure * normative_PPV + disease + n_item + ind_apriori + ind_agreeableness + (1|ResponseId), data = DF)
mod_contrast_renamed = lme4::lmer(error_PPV ~ brochure * `normative PPV` + disease + n_item + `a priori` + ind_agreeableness + (1|ResponseId), data = DF_renamed)

tbl_regression(mod_contrast, show_single_row = everything()) %>%  add_global_p(everything()) %>% as_kable()
#> Registered S3 method overwritten by 'broom.mixed':
#>   method      from 
#>   tidy.gamlss broom
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> add_global_p: Global p-values for variable(s) `include = c("brochure",
#> "normative_PPV", "disease", "n_item", "ind_apriori", "ind_agreeableness",
#> "brochure:normative_PPV")` were calculated with
#>   `car::Anova(x$model_obj, type = "III")`
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">brochure</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">28, 45</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">normative_PPV</td>
<td style="text-align: left;">-24</td>
<td style="text-align: left;">-31, -18</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">disease</td>
<td style="text-align: left;">-2.1</td>
<td style="text-align: left;">-7.0, 2.8</td>
<td style="text-align: left;">0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">n_item</td>
<td style="text-align: left;">6.2</td>
<td style="text-align: left;">1.3, 11</td>
<td style="text-align: left;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ind_apriori</td>
<td style="text-align: left;">0.05</td>
<td style="text-align: left;">-0.10, 0.20</td>
<td style="text-align: left;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">ind_agreeableness</td>
<td style="text-align: left;">-0.20</td>
<td style="text-align: left;">-5.1, 4.7</td>
<td style="text-align: left;">&gt;0.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">brochure * normative_PPV</td>
<td style="text-align: left;">-42</td>
<td style="text-align: left;">-52, -32</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>

``` r
tbl_regression(mod_contrast_renamed, show_single_row = everything()) %>%  add_global_p(everything()) %>% as_kable()
#> add_global_p: Global p-values for variable(s) `include = c("brochure",
#> "normative PPV", "disease", "n_item", "a priori", "ind_agreeableness",
#> "brochure:normative PPV")` were calculated with
#>   `car::Anova(x$model_obj, type = "III")`
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">brochure</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">28, 45</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">normative PPV</td>
<td style="text-align: left;">-24</td>
<td style="text-align: left;">-31, -18</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">disease</td>
<td style="text-align: left;">-2.1</td>
<td style="text-align: left;">-7.0, 2.8</td>
<td style="text-align: left;">0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">n_item</td>
<td style="text-align: left;">6.2</td>
<td style="text-align: left;">1.3, 11</td>
<td style="text-align: left;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">a priori</td>
<td style="text-align: left;">0.05</td>
<td style="text-align: left;">-0.10, 0.20</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">ind_agreeableness</td>
<td style="text-align: left;">-0.20</td>
<td style="text-align: left;">-5.1, 4.7</td>
<td style="text-align: left;">&gt;0.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">brochure * normative PPV</td>
<td style="text-align: left;">-42</td>
<td style="text-align: left;">-52, -32</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>

<sup>Created on 2020-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 18.04.5 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Atlantic/Canary             
#>  date     2020-10-17                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package       * version    date       lib
#>  abind           1.4-5      2016-07-21 [1]
#>  assertthat      0.2.1      2019-03-21 [1]
#>  backports       1.1.10     2020-09-15 [1]
#>  boot            1.3-25     2020-04-26 [4]
#>  broom           0.7.1      2020-10-02 [1]
#>  broom.helpers   1.0.0.9001 2020-10-16 [1]
#>  broom.mixed     0.2.6      2020-05-17 [1]
#>  callr           3.5.1      2020-10-13 [1]
#>  car             3.0-10     2020-09-29 [1]
#>  carData         3.0-4      2020-05-22 [1]
#>  cellranger      1.1.0      2016-07-27 [1]
#>  cli             2.1.0      2020-10-12 [1]
#>  coda            0.19-4     2020-09-30 [1]
#>  crayon          1.3.4      2017-09-16 [1]
#>  curl            4.3        2019-12-02 [1]
#>  data.table      1.13.0     2020-07-24 [1]
#>  desc            1.2.0      2018-05-01 [1]
#>  devtools        2.3.2      2020-09-18 [1]
#>  digest          0.6.25     2020-02-23 [1]
#>  dplyr         * 1.0.2      2020-08-18 [1]
#>  ellipsis        0.3.1      2020-05-15 [1]
#>  evaluate        0.14       2019-05-28 [1]
#>  fansi           0.4.1      2020-01-08 [1]
#>  forcats         0.5.0      2020-03-01 [1]
#>  foreign         0.8-75     2020-01-20 [1]
#>  fs              1.5.0      2020-07-31 [1]
#>  generics        0.0.2      2018-11-29 [1]
#>  glue            1.4.2      2020-08-27 [1]
#>  gtsummary     * 1.3.5.9001 2020-10-15 [1]
#>  haven           2.3.1      2020-06-01 [1]
#>  here          * 0.1        2017-05-28 [1]
#>  highr           0.8        2019-03-20 [1]
#>  hms             0.5.3      2020-01-08 [1]
#>  htmltools       0.5.0      2020-06-16 [1]
#>  knitr           1.30       2020-09-22 [1]
#>  labelled        2.7.0      2020-09-21 [1]
#>  lattice         0.20-41    2020-04-02 [1]
#>  lifecycle       0.2.0      2020-03-06 [1]
#>  lme4          * 1.1-25     2020-10-17 [1]
#>  magrittr        1.5        2014-11-22 [1]
#>  MASS            7.3-53     2020-09-09 [1]
#>  Matrix        * 1.2-18     2019-11-27 [1]
#>  memoise         1.1.0      2017-04-21 [1]
#>  minqa           1.2.4      2014-10-09 [1]
#>  nlme            3.1-149    2020-08-23 [1]
#>  nloptr          1.2.2.2    2020-07-02 [1]
#>  openxlsx        4.2.2      2020-09-17 [1]
#>  pillar          1.4.6      2020-07-10 [1]
#>  pkgbuild        1.1.0      2020-07-13 [1]
#>  pkgconfig       2.0.3      2019-09-22 [1]
#>  pkgload         1.1.0      2020-05-29 [1]
#>  plyr            1.8.6      2020-03-03 [1]
#>  prettyunits     1.1.1      2020-01-24 [1]
#>  processx        3.4.4      2020-09-03 [1]
#>  ps              1.4.0      2020-10-07 [1]
#>  purrr           0.3.4      2020-04-17 [1]
#>  R6              2.4.1      2019-11-12 [1]
#>  Rcpp            1.0.5      2020-07-06 [1]
#>  readr         * 1.4.0      2020-10-05 [1]
#>  readxl          1.3.1      2019-03-13 [1]
#>  remotes         2.2.0      2020-07-21 [1]
#>  reshape2        1.4.4      2020-04-09 [1]
#>  rio             0.5.16     2018-11-26 [1]
#>  rlang           0.4.8      2020-10-08 [1]
#>  rmarkdown       2.4        2020-09-30 [1]
#>  rprojroot       1.3-2      2018-01-03 [1]
#>  sessioninfo     1.1.1      2018-11-05 [1]
#>  statmod         1.4.34     2020-02-17 [1]
#>  stringi         1.5.3      2020-09-09 [1]
#>  stringr         1.4.0      2019-02-10 [1]
#>  testthat        2.3.2      2020-03-02 [1]
#>  tibble          3.0.4      2020-10-12 [1]
#>  tidyr           1.1.2      2020-08-27 [1]
#>  tidyselect      1.1.0      2020-05-11 [1]
#>  TMB             1.7.18     2020-07-27 [1]
#>  usethis         1.6.3      2020-09-17 [1]
#>  vctrs           0.3.4      2020-08-29 [1]
#>  withr           2.3.0      2020-09-22 [1]
#>  xfun            0.18       2020-09-29 [1]
#>  yaml            2.2.1      2020-02-01 [1]
#>  zip             2.1.1      2020-08-27 [1]
#>  source                                   
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  Github (larmarange/broom.helpers@44c81b0)
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.1)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.2)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.2)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.2)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  Github (ddsjoberg/gtsummary@6a7ea47)     
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.1)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.2)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  Github (lme4/lme4@7f6479a)               
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.1)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.1)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.2)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.1)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.2)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.0)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#>  CRAN (R 3.6.3)                           
#> 
#> [1] /home/emrys/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

### PR DESCRIPTION
**Pull request by gorkang**
**What changes are proposed in this pull request?**

Replace back ticks "\`"  in `variable` before `filter(.data$variable %in% !!include)` so the variables with back ticks won't disappear.

**If there is an GitHub issue associated with this pull request, please provide link.**

closes #682

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN=true)` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@gorkang thank you soooo much! This is awesome 😎

@larmarange would you mind reviewing this PR? I don't think I'll have the time in the next few weeks to give it the attention it deserves, AND you're the king of matching variable names! Is there another approach that would be more robust?

**Comment by larmarange** [comment]
@ddsjoberg we had the same problem in broom.helpers. So we had to clean backtips. However, some variables could have characters that would be interpreted as special character in a regular expression (e.g. a variable named `a + b`). And it is better to check if backtips are at the beginning and the end of the variable names.

See https://github.com/larmarange/broom.helpers/blob/6b78a2ad32d026286b394fc3c6d684082fa7d094/R/broom.helpers-package.R#L24

It would be better to use something similar in `gtsummary`. 

A basic function to clean:

```r
# remove backtips around variable names
.clean_backtips <- function(x) {
  for (i in stats::na.omit(x)) {
    if (stringr::str_detect(i, "^`.*`$")) {
      x <- stringr::str_replace_all(
        x,
        .escape_regex(i),
        stringr::str_sub(i, 2, -2)
      )
    }
  }
  x
}
```

**Comment by larmarange** [comment]
In addition, it would be good to add some tests in the PR

**Review by larmarange — CHANGES_REQUESTED** [review]
See the global discussion.

- try to use something like `.clean_backtips()` to avoid an issue with certain types of character in variable name (i.e. characters like + or ? or . who have a specfic meaning in a regular expression)
- add some tests in https://github.com/ddsjoberg/gtsummary/blob/master/tests/testthat/test-add_global_p.R

**Comment by ddsjoberg** [comment]
@larmarange Thank you for the thoughtful review!

@gorkang Do you feel comfortable implementing the suggestions from @larmarange ?  If not, one of us can!

**Comment by gorkang** [comment]
> @larmarange Thank you for the thoughtful review!
> 
> @gorkang Do you feel comfortable implementing the suggestions from @larmarange ? If not, one of us can!

Thanks @larmarange and @ddsjoberg ! If you don't mind I'll try to do it latter today. Cheers!

**Comment by gorkang** [comment]
Just committed the requested changes.

- Switched to `mutate(variable = .clean_backticks(variable))` in the add_global_p.tbl_regression() in add_global_p.R

- Added utils-add_global_p.R including the two functions from https://github.com/larmarange/broom.helpers/blob/6b78a2ad32d026286b394fc3c6d684082fa7d094/R/broom.helpers-package.R .escape_regex() and .clean_backticks(). As a side note, I renamed .clean_backtips() to .clean_backticks() as I believe backti**ck**s is the correct spelling (please correct me if I am wrong)

- Added test in test-add_global_p.R, heavily based on the first test in the same file.

I am not sure about a few things:
- Should .escape_regex() and .clean_backticks() go in utils-add_global_p.R?
- Is the new test complete enough?

Thanks for the opportunity to do this and the help reviewing the changes, although I am sure it takes more time for you to review my code than implementing it yourself.

**Comment by ddsjoberg** [comment]
@gorkang FANTASTIC!

@larmarange if we simplify the the backtick cleaning to this function, everything still seems to work properly.  Is there anything I am missing?
``` r
.clean_backticks <- function(x) {
  ifelse(
    # does string starts and ends with backticks
    stringr::str_detect(stringr::fixed(x), "^`.*`$"),
    # if yes remove first and last character of string
    stringr::str_sub(stringr::fixed(x), 2, -2),
    # otherwise, return original string
    x
  )
}

.clean_backticks(c("marker", "`new + mar/ker`", "`new[.7]marker`"))
#> [1] "marker"        "new + mar/ker" "new[.7]marker"
```

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
@gorkang thanks for having identify the typo

@ddsjoberg you are right. The second argument is not needed here

**Comment by ddsjoberg** [comment]
@gorkang the unit tests look great.  I would just added one more variable to the model that has a regular expression character in it, e.g. `+`. Also, please add a unit test from `tbl_uvregression() %>% add_global_p()`

And I think that the shorted cleaning backticks function can just go at the bottom of `R/add_global_p.R` 

Thanks!

**Comment by gorkang** [comment]
Thanks for the help. I was implementing this and found an issue with the new version of .clean_backticks().

In a model like "hp ~ factor(`number + cylinders`) * `miles per galon` + factor(`type of transmission`)" it misses the interaction  "factor(`number + cylinders`):`miles per galon`".

I was wondering that, given gtsummary::tbl_regression() already uses the .clean_backtips() function from broom.helpers (through the tidy_identify_variables() in tidy_remove_intercept() in tidy_prep()...), wouldn't it be better to make sure we always use the same method for removing backticks?

So, in add_global_p(), variable names need to match in:

 `filter(.data$variable %in% !!include) %>%`

It may avoid some future issues if the method to get the names in `.data$variable` is the same as in `!!include`, right?


If you agree, is there a way to import the broom.helpers version of the function directly instead of copying it? (so if the broom.helpers version changes in the future we make sure we are still using the same function...).


Below there is a reproducible example showing the issue.

``` r
library(dplyr)
library(gtsummary)

# Functions ---------------------------------------------------------------
.escape_regex <- function (string) {
  gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\\1", string )
  }

.clean_backticks_broomhelpers <- function(x, variable_names = x) {
  for (i in stats::na.omit(variable_names)) {
    x <- stringr::str_replace_all(
      x,
      paste0("`", .escape_regex(i), "`"),
      i
    )

    if (stringr::str_detect(i, "^`.*`$")) {
      x <- stringr::str_replace_all(
        x,
        .escape_regex(i),
        stringr::str_sub(i, 2, -2)
      )
    }
  }
  x
}

# Simplified version
.clean_backticks <- function(x) {
  ifelse(
    # does string starts and ends with backticks
    stringr::str_detect(stringr::fixed(x), "^`.*`$"),
    # if yes remove first and last character of string
    stringr::str_sub(stringr::fixed(x), 2, -2),
    # otherwise, return original string
    x
  )
}



# Model -------------------------------------------------------------------
mod1 <- lm(hp ~ factor(`number + cylinders`) * `miles per galon` + factor(`type of transmission`), mtcars %>% rename(`miles per galon` = mpg, `type of transmission` = am, `number + cylinders` = cyl))

table =  tbl_regression(mod1)

# This is the "canonical" version: factor(`number + cylinders`):miles per galon
table$table_body %>% distinct(variable)
#> # A tibble: 4 x 1
#>   variable                                    
#>   <chr>                                       
#> 1 factor(`number + cylinders`)                
#> 2 miles per galon                             
#> 3 factor(`type of transmission`)              
#> 4 factor(`number + cylinders`):miles per galon


# Create anova table
table_anova = table$model_obj %>% car::Anova(type = "III") %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "variable")


# Using the new .clean_backticks():  factor(`number + cylinders`):`miles per galon`
table_anova %>%
  mutate(variable = .clean_backticks(variable)) %>%
  distinct(variable)
#>                                         variable
#> 1                                    (Intercept)
#> 2                   factor(`number + cylinders`)
#> 3                                miles per galon
#> 4                 factor(`type of transmission`)
#> 5 factor(`number + cylinders`):`miles per galon`
#> 6                                      Residuals


# Using .clean_backticks_broomhelpers: factor(`number + cylinders`):miles per galon
table_anova %>%
  mutate(variable = .clean_backticks_broomhelpers(variable)) %>%
  distinct(variable)
#>                                       variable
#> 1                                  (Intercept)
#> 2                 factor(`number + cylinders`)
#> 3                              miles per galon
#> 4               factor(`type of transmission`)
#> 5 factor(`number + cylinders`):miles per galon
#> 6                                    Residuals
```

This is irrelevant for the issue above but that I don't quite understand... .clean_backticks_broomhelpers() works fine when getting `table_anova$variable` as input but not when getting `table_anova$variable[5]`

``` r
# Works
table_anova$variable %>% .clean_backticks_broomhelpers(.)
#> [1] "(Intercept)"                                 
#> [2] "factor(`number + cylinders`)"                
#> [3] "miles per galon"                             
#> [4] "factor(`type of transmission`)"              
#> [5] "factor(`number + cylinders`):miles per galon"
#> [6] "Residuals"

# Do not work
table_anova$variable[5] %>% .clean_backticks_broomhelpers(.)
#> [1] "factor(`number + cylinders`):`miles per galon`"
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
@ddsjoberg if you prefer, I will export (and document) the function from broom.helpers (and add some more strict tests)

**Comment by larmarange** [comment]
Note: the function needs a named vector to work without the second argument. Or you can pass the list of variables as a second argument.

**Comment by gorkang** [comment]
> Note: the function needs a named vector to work without the second argument. Or you can pass the list of variables as a second argument.

Thanks for the clarification @larmarange 

Another issue I am encountering is that the non-standard names do not work at all with `tbl_uvregression()`:

``` r

trial %>% rename(`age + person` = age) %>% tbl_uvregression(method = lm, y = `age + person`)

> Error: Problem with `mutate()` input `model`.
> x object 'age' not found
> ℹ Input `model` is `map(...)`.

```

**Comment by larmarange** [comment]
@gorkang thanks for the feedback. I'm realising that the current cleaning does not work for interaction only terms.

``` r
library(broom.helpers)
lm(
  hp ~ factor(`number + cylinders`) : `miles per galon` + factor(`type of transmission`), 
  mtcars %>% dplyr::rename(`miles per galon` = mpg, `type of transmission` = am, `number + cylinders` = cyl)
) %>% 
  model_identify_variables() %>%
  dplyr::select(term, variable)
#> # A tibble: 5 x 2
#>   term                                    variable                              
#>   <chr>                                   <chr>                                 
#> 1 (Intercept)                             <NA>                                  
#> 2 factor(`type of transmission`)1         factor(`type of transmission`)        
#> 3 factor(`number + cylinders`)4:`miles p~ factor(`number + cylinders`):`miles p~
#> 4 factor(`number + cylinders`)6:`miles p~ factor(`number + cylinders`):`miles p~
#> 5 factor(`number + cylinders`)8:`miles p~ factor(`number + cylinders`):`miles p~
```

I just opened an issue for `broom.helpers`: https://github.com/larmarange/broom.helpers/issues/67

I need to pass a list of variables to `..clean_backticks` where appropriate

**Comment by larmarange** [comment]
@gorkang and @ddsjoberg 

I have been reexploring different complex cases (non-standard names, use of characters that have a meaning in a regex, variables names containing a colon (:), interaction only terms...)

Following this, I made the following changes in `broom.helpers`:

- I have updated `.clean_backticks()` 
- `.clean_backticks()` is now exported by `broom.helpers`
- to properly take into account interaction only terms, it is necessary to pass a second argument to `.clean_backticks()`. The easiest is `model %>% model_list_variables(only_variable = TRUE)` that list all variables used in a model, even if they are used only in an interaction

Note: in a `tbl_regression()` object, the original model is stored in `model_obj`

**Comment by ddsjoberg** [comment]
Hey @gorkang !  Can you push your updates to your branch?  I'll steal your updated code to fix the `tbl_uvregression()`! 💯

**Comment by gorkang** [comment]
> Hey @gorkang ! Can you push your updates to your branch? I'll steal your updated code to fix the `tbl_uvregression()`!  Then we'll merge all the updates together.

OK, done. Hoefully it's somehow useful.

One thing though. A bunch of the tests give a `partial argument match of 'corr' to 'correlation'` warning. I believe it is located in the `car::Anova(model)`. Probably not important, but wanted to let you know.

**Comment by ddsjoberg** [comment]
Hey @gorkang ! 

Thank you so much for your work on this.  I took a look at the `tbl_uvregression()` bug with non-standard names.  Oooooof! It's going to be a larger fix than I originally thought. I thought it would be a small fix to the `car::Anova()` data frame, but the errors start much earlier in the function! 

Would it be feasible to remove the `tbl_uvregression()` updates you've made (and unit tests), and we can review and merge as the `tbl_regression()` fix on its own?

**Comment by gorkang** [comment]
> Hey @gorkang !
> 
> Thank you so much for your work on this. I took a look at the `tbl_uvregression()` bug with non-standard names. Oooooof! It's going to be a larger fix than I originally thought. I thought it would be a small fix to the `car::Anova()` data frame, but the errors start much earlier in the function!
> 
> Would it be feasible to remove the `tbl_uvregression()` updates you've made (and unit tests), and we can review and merge as the `tbl_regression()` fix on its own?

Sorry to hear that. OK, just reverted the changes.

**Comment by ddsjoberg** [comment]
@gorkang @larmarange

Thanks @gorkang for the `tbl_uvregression()` update. 

I added a `Remotes:` to broom.helpers in the `DESCRIPTION` file so the continuous integration checks use the dev version instead of the CRAN version (so this PR will pass all the checks).  I'll remove before the next gtsummary release.

Thank you both for your work on this important PR. @larmarange is it ready for merging, or more checking first?

**Comment by larmarange** [comment]
For me it's OK.

Let me know when you would like me to release a new version of brrom.helpers

**Comment by ddsjoberg** [comment]
Great!  I'll merge!

Regarding the next release of broom.helpers, please let me first finish the integration of the updates into gtsummary...just to make sure there is nothing else needing updating in broom.helpers.

**Pull request merged**
