### PR TITLE
LHS of formula env bug fix

### LINKED ISSUE #604: Improved handling of LHS of formula in tidyselet_to_list()
We recently implemented for careful handling of environments for the evaluation of the RHS of formula lists passed as args in gtsummary (#599).  The same care needs to be made for the RHS.  It is somewhat more complicated, because the LHS can always be evaluated, while the RHS is often bare tidyselectors.....need to think on how to do this.

```r
no_fun <- function() {
  grade_level = "test"
  s <- '{mean}'
  label_var = "grade"
  trial %>%
    tbl_summary(
      label = label_var ~ paste("Grade", grade_level), 
      statistic = all_continuous() ~ s
    )
}
no_fun()
```

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
There was an environments bug when evaluating the LHS of the formula inputs.  In some complex situations, a stored character vector of column names could not properly evaluate (example in #604).

The solution was to save the formula environment, and pass it to the selecting functions.  When the `enquo()` was created, I replaced the quoted environment with the formula environment.

 All of these selecting functions work well at this point (I hope!), but can certainly be cleaned up 😬 (#648)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #604 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN=true)` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by michaelcurry1123** [comment]
@ddsjoberg  The examples in #604 work but if you nest the example within two functions then it might give unexpected results: 


```
super_fun <- function(){
  no_fun <- function() {
    grade_level = "test"
    s <- '{mean}'
    label_var = "grade"
    trial %>%
      tbl_summary(
        label = glue::glue("{label_var} ~ \"{paste('Grade', grade_level)}\"") %>% as.formula(), 
        statistic = all_continuous() ~ s
      )
  }
}
#no output here
super_fun()

try_fun <- super_fun()
#now it outputs
try_fun()
```

My guess is rlang::f_env() evaluates to the super_fun() env but then it will not print to the viewer/global env. I think once you store the double function in try_fun and then evaluate it that is how it goes up two environments. 
Thoughts? I can see this might be an issues if someone is looping a custom function perhaps?

**Comment by ddsjoberg** [comment]
@michaelcurry1123 i think the issue in the example is that `super_fun()` doesn't return anything and doesn't execute `no_fun()`?

**Comment by michaelcurry1123** [comment]
@ddsjoberg I think you are right this works : 
```
super_fun <- function(){
   no_fun <- function() {
    grade_level = "test"
    s <- '{mean}'
    label_var = "grade"
    trial %>%
      tbl_summary(
        label = glue::glue("{label_var} ~ \"{paste('Grade', grade_level)}\"") %>% as.formula(), 
        statistic = all_continuous() ~ s
      )
   }
   no_fun()
}
```

but it is interesting that this does not: 
`super_fun <- function(){
   no_fun <- function() {
    grade_level = "test"
    s <- '{mean}'
    label_var = "grade"
    trial %>%
      tbl_summary(
        label = glue::glue("{label_var} ~ \"{paste('Grade', grade_level)}\"") %>% as.formula(), 
        statistic = all_continuous() ~ s
      )
   }
   no_fun()
}`

**Comment by ddsjoberg** [comment]
@michaelcurry1123 I think that second example would only return a function object and it's never executed?

**Review by michaelcurry1123 — APPROVED** [review]

**Pull request merged**
