### PR TITLE
added default separators for IQR  and CIs

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
When someone uses the language theme to set the decimal marker to `","`, the comma separating the IQR and the confidence intervals could be more difficult to read. This update sets those separators to `" - "` when the decimal mark is a comma.

image

**If there is an GitHub issue associated with this pull request, please provide link.**

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN = TRUE)` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@oranwutang is something like this useful? would you modify it in some way?

**Comment by oranwutang** [comment]
Hi Daniel, I don't think it is useful, I think it is essential!
Certainly, this is the correct way to separate digits in Spanish.

**Comment by ddsjoberg** [comment]
@oranwutang great!

I added an en dash separator since it looks a bit nicer. The output seems to work with `as_tibble()`, `as_gt()`, `as_kable()`, `as_kable_extra()`, `as_flex_table()`, and `as_hux_table()` too!

Non-ASCII always make me a little nervous haha. Can you confirm it works on your machine before I merge it? 

```r
library(gtsummary)
theme_gtsummary_language("en", big.mark = " ", decimal.mark = ",")

trial %>%
  tbl_uvregression(
    y = response,
    method = glm,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_flex_table()

trial %>%
  select(age, trt) %>%
  tbl_summary() %>%
  as_gt()
```

image

image

**Comment by oranwutang** [comment]
I have installed language_defaults branch and tried your code, it works perfectly:

image

image

By the way, I couldn't help trying the Japanese theme, I'm freaking with it 🍱🍣!

image

**Comment by ddsjoberg** [comment]
YAY! They look great! I almost prefer the en dash to the comma for all the tables! oy!

**Comment by oranwutang** [comment]
I agree, the en dash is a nice solution for separating numbers

**Pull request merged**
