### PR TITLE
Add hierarchy group levels to `table_body` in `tbl_hierarchical()`

### LINKED ISSUE #2070: Add variable levels to `tbl_hierarchical()*` table body
We will need the levels stored inside the table body in order to sort and filter based on various conditions (e.g. the prev.).

### PR DESCRIPTION
**Pull request by edelarua**
**What changes are proposed in this pull request?**

* Added columns to `table_body` as returned by `tbl_hierarchical()` to keep information on all hierarchy levels.

Closes #2070 

@ddsjoberg 2 questions:
- What do we want to name these columns? `variableXX` and `variableXX_level`? I wasn't sure since we already have a `variable` column in `table_body` so I left it as `groupXX` and `groupXX_level` for now.
- Do we want to add the innermost level as well even though it should always be represented by `variable` where applicable?

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] PR branch has pulled the most recent updates from main branch.
- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Thank you @edelarua !

> What do we want to name these columns? variableXX and variableXX_level? I wasn't sure since we already have a variable column in table_body so I left it as groupXX and groupXX_level for now.

I think that is perfect.

> Do we want to add the innermost level as well even though it should always be represented by variable where applicable?

Probably don't need it right?

**Comment by ddsjoberg** [comment]
this is great, i love it! Can we make one small change? Can you move the grouping columns to after the `row_type` column? I prefer keeping all the hidden column grouped together in the beginning of the data frame.

**Review by ddsjoberg — CHANGES_REQUESTED** [review]
this is great, i love it! Can we make one small change? Can you move the grouping columns to after the `row_type` column? I prefer keeping all the hidden column grouped together in the beginning of the data frame.

**Comment by edelarua** [comment]
> this is great, i love it! Can we make one small change? Can you move the grouping columns to after the `row_type` column? I prefer keeping all the hidden column grouped together in the beginning of the data frame.

Done!

**Review by ddsjoberg — APPROVED** [review]
Lovely, thank you @edelarua !

**Pull request merged**
