### PR TITLE
added competing events support to `tbl_survfit()`

### LINKED ISSUE #64: tbl_survival to handle cuminc from cmprsk package
This will allow people to get cumulative incidence for competing risks for each event.

### LINKED ISSUE #448: tbl_survfit and competing risks
1. What happens when output from `survival::finegrey()` is passed to `survival::survfit()`?  
1. Can that output be passed to `tbl_survfit()`?

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
Updated `tbl_survfit()` to handle competing events.  Added example to help file.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #64
closes #448

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch 
- [x] NEWS.md has been updated under the heading "`# gtsummary (development version)`"?
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] If a new function was added, function included in `pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by michaelcurry1123** [comment]
@margarethannum  @ddsjoberg   Nicely done! I think once this is implemented it will be a huge!

1. How does the new function accept `cuminc` objects? I seem to get an error when I try this:

```
cmod <-
  cmprsk::cuminc(ftime = mgus2_ds$etime, 
                 fstatus = mgus2_ds$event, 
                 group = mgus2_ds$sex)

gtsummary::tbl_survfit(cmod, probs = .5)

```
The error states there is no tidy method for cuminc. 

2. Also I noticed that the functions are using `mutate_at`, while these are not depreciated, all of the *_all, *_if, and *_at functions are being superseded in dplyr with across. See here: https://dplyr.tidyverse.org/news/index.html?q=across#across 

>  Superseded
> The scoped helpers (all functions ending in _if, _at, or _all) have been superseded by across(). This dramatically reduces the API surface for dplyr, while at the same providing providing a more flexible and less error-prone interface (#4769).
> 

3. More of a question: should finegray and mutli-state models produce similar results? These two output give pretty different answers (to be honest I don't know much about mutli-state models above cumulative incidence curves so if this is a dumb questions please ignore)


```
trial2 <- trial %>%
  mutate(
    death_cr = case_when(
      death == 0 ~ "censor",
      runif(n()) < 0.5 ~ "death from cancer",
      TRUE ~ "death other causes"
    ) %>% factor()
  )

survfit(Surv(ttdeath, death_cr) ~ grade, data = trial2) %>%
  tbl_survfit(times = c(12, 24), label = "Tumor Grade")



trial3 <- finegray(Surv(ttdeath, death_cr) ~ ., data = trial2)

survfit(Surv(fgstart, fgstop, fgstatus) ~ grade,
        weight = fgwt, data = trial3) %>%
  gtsummary::tbl_survfit(times = c(12, 24), reverse = TRUE)

```

**Comment by ddsjoberg** [comment]
Thank you for reviewing @michaelcurry1123 !! Responses below :)

> @margarethannum @ddsjoberg Nicely done! I think once this is implemented it will be a huge!
> 
> 1. How does the new function accept `cuminc` objects? I seem to get an error when I try this:
> 
> ```
> cmod <-
>   cmprsk::cuminc(ftime = mgus2_ds$etime, 
>                  fstatus = mgus2_ds$event, 
>                  group = mgus2_ds$sex)
> 
> gtsummary::tbl_survfit(cmod, probs = .5)
> ```
> 
> The error states there is no tidy method for cuminc.

We only accept competing risk cum inc estimates calculated from `survival::survfit()` (https://cran.r-project.org/web/packages/survival/vignettes/compete.pdf).  We do this because there are tidy methods for it, where the cmprsk package doesn't have them.  What do you think we should do to make this more clear?  Perhaps at least a check at the top that the object passed is a class from `survival::survfit()` ?

> 1. Also I noticed that the functions are using `mutate_at`, while these are not depreciated, all of the *_all, *_if, and *_at functions are being superseded in dplyr with across. See here: https://dplyr.tidyverse.org/news/index.html?q=across#across
> 
> > Superseded
> > The scoped helpers (all functions ending in _if, _at, or _all) have been superseded by across(). This dramatically reduces the API surface for dplyr, while at the same providing providing a more flexible and less error-prone interface (#4769).

We would need to update gtsummary to depend on dplyr 1.0 to use those functions. Since dplyr 1.0 does have some breaking changes in it, we opted not to require it at this time. (But there are those and other functions that will make things easier I am looking forward to using in the future!)

> 1. More of a question: should finegray and mutli-state models produce similar results? These two output give pretty different answers (to be honest I don't know much about mutli-state models above cumulative incidence curves so if this is a dumb questions please ignore)
> 
> ```
> trial2 <- trial %>%
>   mutate(
>     death_cr = case_when(
>       death == 0 ~ "censor",
>       runif(n()) < 0.5 ~ "death from cancer",
>       TRUE ~ "death other causes"
>     ) %>% factor()
>   )
> 
> survfit(Surv(ttdeath, death_cr) ~ grade, data = trial2) %>%
>   tbl_survfit(times = c(12, 24), label = "Tumor Grade")
> 
> trial3 <- finegray(Surv(ttdeath, death_cr) ~ ., data = trial2)
> 
> survfit(Surv(fgstart, fgstop, fgstatus) ~ grade,
>         weight = fgwt, data = trial3) %>%
>   gtsummary::tbl_survfit(times = c(12, 24), reverse = TRUE)
> ```

If the underlying data are perfectly proportional hazards, then I think they would be the same.  But I do think part of the review process should check the results against `cmprisk::cuminc()` output for various situations.

**Comment by michaelcurry1123** [comment]
@ddsjoberg thank you Dan! The message says this right now ` Error: No tidy method for objects of class cuminc `, I think it would be great it is could say something like ` Error: No tidy method for objects of class cuminc, please use survfit() to estimate cumulative incidences` or something like that. But I would like to hear your thoughts on it. Point 2 is fine above but it will be interesting to see what `dplyr`s move to the `vctrs` package does to some of the functions. Point 3 is great I think it would be interesting to check against cuminc to survfit and `survival::finegray()` to `cmprsk::crr()`

**Comment by ddsjoberg** [comment]
> @ddsjoberg thank you Dan! The message says this right now `Error: No tidy method for objects of class cuminc`, I think it would be great it is could say something like ` Error: No tidy method for objects of class cuminc, please use survfit() to estimate cumulative incidences` or something like that. But I would like to hear your thoughts on it. Point 2 is fine above but it will be interesting to see what `dplyr`s move to the `vctrs` package does to some of the functions. Point 3 is great I think it would be interesting to check against cuminc to survfit and `survival::finegray()` to `cmprsk::crr()`

1. I added a check for the class of the argument `x=` to ensure the object passed was created from `survival::survfit()`. 

3. Do you want to add a test to `test-tbl_survfit.R` comparing the output from `tbl_survfit()` and `cmprsk::cuminc()`?  You would need to add the cmprsk package to the Suggests section in the DESCRIPTION file with `usethis::use_package("cmprsk", type = "Suggests")`

@michaelcurry1123 🕺

**Comment by michaelcurry1123** [comment]
changes to number 1 look great. I don't think that the 3rd one is super necessary do you? what would that check help with? I manually checked and saw the estimates are the same. If there were differences between survival and cmprsk it would have to do with their methodologies not the display from gtsummary right? after we talk about this I think it is ready from my perspective!

**Comment by ddsjoberg** [comment]
> changes to number 1 look great. I don't think that the 3rd one is super necessary do you? what would that check help with? I manually checked and saw the estimates are the same. If there were differences between survival and cmprsk it would have to do with their methodologies not the display from gtsummary right? after we talk about this I think it is ready from my perspective!

The benefit of the check against cmprsk is that all future updates will make the check to make sure we don't mess it up haha. But I think a check against the raw `survival::survfit()` updates would be best to make sure we don't mess it up would be helpful.

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I made a change to the unit test for competing risks. In tbl_survival do you think people would want n at risk and number of events option or is that too much for one table?

**Comment by ddsjoberg** [comment]
> @ddsjoberg I made a change to the unit test for competing risks. In tbl_survival do you think people would want n at risk and number of events option or is that too much for one table?

I think that could be useful. It would be an update for competing events and regular KM estimates.  Would you like to implement this in a separate PR? @michaelcurry1123

**Comment by michaelcurry1123** [comment]
@ddsjoberg  happy to do that!

**Pull request merged**
