### PR TITLE
Portuguese language updates

### LINKED ISSUE #1098: Bug Report: update pt translations
This issue is a followup to #1097. It includes some translations of commonly used strings in `gtsummary` for the pt language:

**New strings:**
- added two new lines in add_p.tbl_summary for McNemar test (with/ without continuity correction)
- added a new line for Paired t-test
- SE / standard error

**Changes to previously translations:**
- t-test: now mentions Welch correction (as per the en string)
- RR: translated as Risk Ratio (instead of Relative Risk)
- CI (et al):  changed to IC in pt (similar to fr)
- p-value: Capitalized (for consistency with q-value)
- One-way ANOVA: different choice of translation, consistent with books/tutorials in pt
- random intercept logistic regression: transation is now closer to the original meaning
- IQR: translated as AIQ
- Variance

Note that the RR string is proposed to change (from relative risk to risk ratio). If this is not approriate, let me know and I will revert the translation back to "relative risk".

Attached below is a CSV with all lines changed from `data-raw/gtsummary_translated.xlsx `

[pt_updates.csv](https://github.com/ddsjoberg/gtsummary/files/7833898/pt_updates.csv)

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**

* Updates and additions to Portuguese language translations. (#1098)

**If there is an GitHub issue associated with this pull request, please provide link.**

closes #1098

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Thank you @philsf for the improvements to the translations!! 👐🏼 👐🏼 👐🏼 👐🏼 

Can you please take a look to check I didn't make an error in the copy and pasting of the translations?

**Comment by ddsjoberg** [comment]
Thank you @philsf for the quick updates!!

**Comment by philsf** [comment]
@ddsjoberg sorry, but I was testing with the paired dataset, and assumed the paired_wide would work the same. I just noticed the translation DOES NOT kick in when using `mcnemar.test.wide` for some reason. Is it being collected from a different source, other than the XLSX/CSV I provided?

**Comment by ddsjoberg** [comment]
> @ddsjoberg sorry, but I was testing with the paired dataset, and assumed the paired_wide would work the same. I just noticed the translation DOES NOT kick in when using `mcnemar.test.wide` for some reason. Is it being collected from a different source, other than the XLSX/CSV I provided?

Thank you VERY MUCH for the checking. I looked into the issue and ALL translated p-value footnotes were being reset back to English. Should be updated now. Can you confirm on your end? @philsf

**Comment by philsf** [comment]
This is amazing, thank you very much for this @ddsjoberg.

It now does what is says on the tin. I believe all tests are correctly translated to pt, in all functions I tested. Can'th thank you enough.

The sad part is: the translations made so far work, but the package is not yet fully translated bc I used the previously translated strings as a base, and added a few I usually come by in day2day - but to make a proper list of translation I would need to figure out all tests/methods/models available and include the strings in the template. I will be delighted to help add more strings in the future, but I don't think you should wait to merge what was done so far.

*perfect is the enemy of good* (or something like that)

**Comment by ddsjoberg** [comment]
@philsf please feel free to add whenever you have time!

**Pull request merged**
