### PR TITLE
adopts testthat 3 edition

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
There are two tests in `test-add_p.tbl_svysummary` that fail, and I have no idea why! 

Otherwise, everything else is working as expected after these changes.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
WOW! Thank you so much! 🙌🏼 🙌🏼 🙌🏼

**Comment by ddsjoberg** [comment]
I _think_ those new failures may be because waldo is using a relative difference rather than an absolute.   I can just increase the tol level...I'll look into it more this weekend!

**Comment by ddsjoberg** [comment]
@IndrajeetPatil thank you again for this amazing PR!

There are a few more tests (all named `test-vetted_models-<model_name>.R`) that I have set to only run on GitHub Actions.  They still contain the deprecated `expect_equivalent()`.  I can update them if you don't want to.  I would just change them all to `expect_equal()`?

**Comment by ddsjoberg** [comment]
@IndrajeetPatil 👐🏼 👐🏼 👐🏼 👐🏼 👐🏼 thank you so much for upgrading testthat!!

**Comment by IndrajeetPatil** [comment]
Yaay!! 😊

**Pull request merged**
