### PR TITLE
v2.0 Add unit tests for `as_hux_table` and `as_hux_xlsx`

### PR DESCRIPTION
**Pull request by edelarua**
**What changes are proposed in this pull request?**

Add v2.0 unit tests for `as_hux_table` and `as_hux_xlsx`.

Part of https://github.com/insightsengineering/sme-tasks/issues/689

Closes https://github.com/insightsengineering/sme-tasks/issues/701 and https://github.com/insightsengineering/sme-tasks/issues/702

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] Ensure all package dependencies are installed: `renv::install()`
- [ ] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by edelarua** [comment]
@ddsjoberg is the `include` argument meant to be usable in `as_hux_xlsx`? I'm not able to get it to work in my tests but not sure of a situation where it would be used.

**Comment by edelarua** [comment]
Also, should I be testing the contents of the .xlsx file output? From what I can see `as_hux_xlsx` essentially just writes the output of `as_hux_table` to a file, so I'm not sure how in-depth you'd like testing to be.

**Comment by ddsjoberg** [comment]
> @ddsjoberg is the `include` argument meant to be usable in `as_hux_xlsx`? I'm not able to get it to work in my tests but not sure of a situation where it would be used.

I think it's fine as it is. No one has mentioned in all these years, so maybe not needed

**Comment by ddsjoberg** [comment]
> Also, should I be testing the contents of the .xlsx file output? From what I can see `as_hux_xlsx` essentially just writes the output of `as_hux_table` to a file, so I'm not sure how in-depth you'd like testing to be.

I think we can rely on the testing within huxtable that their export function works properly. 🤞🏼

**Review by ddsjoberg — APPROVED** [review]
this is great! thank you!!!!

**Pull request merged**
