### PR TITLE
follow tidyverse style guide

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
As outlined here: https://style.tidyverse.org/

Done using `styler` package: https://styler.r-lib.org/

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I understand this is a massive change for a single PR, but I am not sure how else would you rather have me go about this. 

Making PR for every file doesn't make sense. So let me know what your preference is, and I can modify the PR accordingly.

**Comment by ddsjoberg** [comment]
hey hey! so much style here! 😆 

the package was in need of doing this again...it had been quite some time since it was last run! it is on my list to implement automatic linters of the code to keep it nice, but haven't gotten around to it!

The only problem with merging this as is, is that there are two large PRs underway at the moment that make changes to many many many many files. I think if we merge now, it'll introduce merge conflicts 😨 

Once these two PRs are merged, we can do this one!
https://github.com/ddsjoberg/gtsummary/pull/748
https://github.com/ddsjoberg/gtsummary/pull/603

**Comment by IndrajeetPatil** [comment]
Absolutely! I will close this for now and re-open later on.

I will submit another `PR` to change to `testthat` 3rd edition with parallel support to speed up testing. Is that okay?

**Comment by ddsjoberg** [comment]
OMG I would love that! Thank you, thank you, thank you!

I think I use `context()` in every file, which I think is now deprecated, and probably a bunch of other stuff too that isn't good practice!  :stuck_out_tongue_winking_eye:

**Comment by IndrajeetPatil** [comment]
Cool, will do that 😄

**Pull request closed without merging**
