### PR TITLE
Updates to `as_kable_extra()` 

### LINKED ISSUE #1154: Overhaul `as_kable_extra()`
(continued from https://github.com/shannonpileggi/gtreg/pull/91) cc @shannonpileggi 

- [x] Remove `as_kable_extra(strip_md_bold=)` argument, but continue to strip bold markings for HTML and PDF with `escape = TRUE` output.
- [x] When user passes `as_kable_extra(escape=)` argument, add it to `kableExtra::add_header_row(escape=)`
- When output type is PDF, i.e. `knitr::is_latex_output()` AND user specified `escape = FALSE`
    - [x] Convert markdown bold and italic formatting to latex
    - [x] Use `kableExtra::linebreak()` to style the column names and the header rows. We require the the linebreaker to be `\n`,

Previously, we discussed making `escape=FALSE` the default (which would be a breaking change for nearly every user of this function), but if we use the model above there are no breaking changes (I think)

- [ ] The `as_kable_extra()` function help file needs a refresh....discuss with @shannonpileggi . The examples need updating too.
- [ ] Does any of this new functionality belong in `as_kable()`?
- [ ] Use the `.strip_markdown()` function in the other `as_*()` functions that have the strip md argument.
- [ ] should we remove the `fmt_missing=` argument (only added in the last release)
- [ ] update the `as_kable_extra()` help file images
- [ ] Should we escape the special characters for the users? `gsub("([#$%&_{}])", "\\\\\\1", x)` it's hard...these need to be escaped in the table, but not in the footnotes, meaning that the users would need to both manually specify the stats with the escaped characters in `tbl_summary("\\%")` and update the footnote to _not_ have the escaped characters.  Ooof, should probably do it for them...
- [ ] The argument `escape_table_body=` was added....should we keep it? should the lgl values be flipped to match `escape=`? better name?

### PR DESCRIPTION
**Pull request by ddsjoberg**
### Improvements to `as_kable_extra()`
* For users who used the default kableExtra print without output-specific formatting, there are no breaking changes...the only changes will be improved output styling.
* The biggest user-facing change is that the default results for **LaTeX output** are now greatly improved compared to previous releases, when `escape=FALSE` (the new default).
  - Markdown for bold, italic, and underline are converted to LaTeX code in the column headers and spanning headers.
  - Special LaTeX characters in the body of the table will be escaped with `.escape_latex()` or `.escape_latex2()`, e.g. `%` will be updated to `\\%`, and rendered as `%` in the PDF document.
  - The `"\n"` will be recognized as a line break in the column headers and spanning headers.
  - `\n` is removed from footnotes 
  - The `escape=` argument is now passed to `kableExtra::add_header_row()` and `kableExtra::footnote()` as well (previously, was only passed to `knitr::kable()`).
* The `as_kable_extra(escape=, format=)` arguments have been made explicit, where previously, these arguments were passed via `...`.
* *Breaking Change* The default value of `escape=` is now `FALSE`.  If users previously used `as_kable_extra(escape=FALSE)` and had manually escaped LaTeX/HTML characters in the body of the table, these characters will now be double escaped. To print the table without the auto-escaping that is now present, utilize the new argument `as_kable_extra(addtl_fmt=FALSE)`
* *Breaking Change* The `fmt_missing=` argument was added to `as_tibble()`, `as_kable()`, and `as_kable_extra()` in the last release. This argument is now deprecated in `as_kable()` and `as_kable_extra()`. If a user does not want missing values formatted, they can exclude these commands with the `include=` argument. 
* *Breaking Change* The `strip_md_bold=` has been deprecated. The markdown syntax will automatically be stripped from headers, unless `escape = FALSE` and `format = "latex"`. In that case, the markdown syntax will be converted to LaTeX commands.
* **HTML Updates** With the new default `as_kable_extra(escape=FALSE, addtl_fmt = TRUE)`, the headers, spanning headers, footnotes, captions, and table body are escaped with `.escape_html()`. `\n` is removed from footnotes. To omit the escaping, use `as_kable_extra(addtl_fmt=FALSE)`.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #1154

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by shannonpileggi** [comment]
This works beautifully.  

1. I updated my example .Rmd from my last blog post and the syntax is much, much simpler (shown below).  
2. I tested an example from {gtreg} and it also works great!

Of course, there could be some edge cases we don't anticipate, but overall this really eases the user experience. What a wonderful and welcome addition!

Regarding documentation:
1. Yes, I would encourage users to use `as_kable_extra()` for enhanced pdf printing; for html output options there is better support in the default output.
2. In Usage, `format = ifelse(knitr::is_latex_output(), "latex", "html"),` might be confusing. Are users supposed to specify? Is it automatically detected?
3. It is probably worth trying to add a brief sentence on what `escape` does, as I do mental gymnastics too every time I face it. Something like 
 > `escape` informs if special characters should be escaped when {gtsummary} automatically renders LaTeX typesetting instructions via {kableExtra}, including in `kableExtra::add_header_above()` and `kableExtra::linebreak()`.  
4. I am guess you don't want things to break, but should the default be `escape = TRUE` when the typesetting functionality only works with `escape = FALSE`? I am sure you have already thought about this deeply and there is a very good reason for this.


```
```{r}
tbl_ae_ex1 <-
df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade,
    strata = trt
  ) %>%
  modify_ae_header(all_ae_cols() ~ "**Grade {by}**")
```


```{r}
tbl_ae_ex1 %>% 
  bold_labels() %>% 
  gtsummary::as_kable_extra(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    longtable = TRUE,
    linesep = ""
    ) %>%
  kableExtra::kable_styling(
      position = "left",
      latex_options = c("striped", "repeat_header"),
      stripe_color = "gray!15"
    )
```
```

![image](https://user-images.githubusercontent.com/17747575/154882178-aa99d412-dfe1-4b44-ace6-90af080d4af5.png)





```
## Default column names

```{r}
penguins %>% 
  gtsummary::tbl_summary(
    by = species
  ) %>% 
  gtsummary::bold_labels() %>% 
  gtsummary::as_kable_extra(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    longtable = TRUE,
    linesep = ""
    ) %>%
  kableExtra::kable_styling(
      position = "left",
      latex_options = c("striped", "repeat_header"),
      stripe_color = "gray!15"
    )
```



## Custom column names


```{r}
tbl <- penguins %>% 
  gtsummary::tbl_summary(
    by = species,
    statistic = list(all_categorical() ~ "{n} ({p}%)")
  ) %>%
  bold_labels() %>%
  modify_header(
    all_stat_cols() ~ "**{level}**\nN = {n}"
  )
```



```{r}
tbl %>% 
  gtsummary::as_kable_extra(
    format = "latex",
    booktabs = TRUE,
    longtable = TRUE,
    linesep = "",
    escape = FALSE
    ) %>%
  kableExtra::kable_styling(
      position = "left",
      latex_options = c("striped", "repeat_header"),
      stripe_color = "gray!15"
    )
```
```

**Comment by ddsjoberg** [comment]
@shannonpileggi since we're auto-escaping the table for latex format, I think we should mirror that by escaping the HTML table. I'll add that now.

**Comment by ddsjoberg** [comment]
At the moment, this is the only command run on character columns with `escape = FALSE` and `format = "latex"` to escape the columns `~gsub("([#$%&_{}])", "\\\\\\1", x = .x)`. BUT, the `kableExtra:::escape_latex()` function has many more items that are escaped....do I need to use that function (or a copy of it)?

**Comment by ddsjoberg** [comment]
Hmmmmm, so I tried to use `kableExtra:::escape_latex()` on the table body. I added a `linebreak()` inside the escaping function.

The following issues
1. `linebreak()` has an align arg, that needs to match the assignment from the gtsummary object
2. The `tbl_summary(statistic=)` argument plays multiple roles: defines the statistic in the table body, and used to create the footnote. If a user puts a linebreak in the statistic, the statistic footnote doesn't work with the linebreak.

**Comment by shannonpileggi** [comment]
I can't attach all of the test files here - .Rmd and .html are unsupported file types. I think it might be best to talk through some of this.

**Comment by ddsjoberg** [comment]
@shannonpileggi thanks for looking! You can add them in a zip file if that helps. Let's chat this week

**Comment by ddsjoberg** [comment]
1. I updated the first comment in this PR to reflect the updates that were made.
2. Doing some more testing, the special characters for LaTeX output are not being escaped in the headers, spanning headers, and footnotes.
3. For both HTML and LaTeX, what to do about captions and source notes????

**Comment by shannonpileggi** [comment]
These updates are amazing!! They make beautiful tables so much easier. 🎉

Is it fair to say that the `escape` and `addtl_fmt` only apply to the formatting of the header/spanning header and not necessarily the formatting of the labels and levels? So basically everything in `tbl[["table_styling"]][["header"]]`? If so maybe we could clarify in the docs - I am happy to take a pass at it, but wanted to confirm first.

**Pull request merged**
