### PR TITLE
Allow for grouping variable in tibble/flextable output

### LINKED ISSUE #548: Make `tbl_stack(group=)` compatible with `as_tibble()`
Also, then check output for `as_flextable()` and `as_huxtable()`

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
Grouping variable from `tbl_stack(group_header=)` is now respected in `as_tibble()` and `as_flextable()`. Also includes a fix for `as_flextable()` where the spanning header was grouped incorrectly.

To do:
- [x] Add theme element for grouping column header

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #548 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch 
- [x] NEWS.md has been updated under the heading "`# gtsummary (development version)`"?
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] If a new function was added, function included in `pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
```r
library(gtsummary)
library(flextable)
tt <- trial %>% select(age, grade, trt) %>% tbl_summary(by = trt)

tbl_stack(list(tt, tt), group_header = c("T1", "T2")) %>%
  as_flextable(group_header = "**Table ID**")
```
image

**Comment by ddsjoberg** [comment]
> This is such a great addition to `tbl_stack`!
> 
> I tested and was able to get results as expected. I was wondering if two additions to this update are possible:
> 
> 1 - Is it possible to update the group_header argument to be interpreted with md in order to get bolded header rows (similar to the tab_spanner argument to tbl_merge)? Am thinking of something like the following:
> 
> ```
> tbl_A <- trial %>% 
>   select(age, marker, trt) %>% 
>   tbl_summary(by = trt)
> 
> tbl_B <- trial %>% 
>   select(grade, response, trt) %>% 
>   tbl_summary(by = trt)
> 
> tbl_stack(list(tbl_A, tbl_B), group_header = c("**first table**", "**second table**"))
> ```

This is a fantastic suggestion, @jalavery ! Would you be interested in making the update? It would require an update to `as_gt()`. I've never tried to make this work with a group header, but expect it is possible with {gt}?

> 2 - If passing a named list to tbl_stack, could the group_header argument automatically populate with the names from the list?
> 
> I don't have a sense of how involved either of these updates are, but wanted to mention them as potentially useful features. If not on the priority list for right now, I can go ahead and complete and approve the rest of the review.

Can we think on this one more, discuss, and perhaps update in a future pull request?  How would the users turn off the group headers if we auto populated with the names from the list?

**Comment by jalavery** [comment]
> > This is such a great addition to `tbl_stack`!
> > I tested and was able to get results as expected. I was wondering if two additions to this update are possible:
> > 1 - Is it possible to update the group_header argument to be interpreted with md in order to get bolded header rows (similar to the tab_spanner argument to tbl_merge)? Am thinking of something like the following:
> > ```
> > tbl_A <- trial %>% 
> >   select(age, marker, trt) %>% 
> >   tbl_summary(by = trt)
> > 
> > tbl_B <- trial %>% 
> >   select(grade, response, trt) %>% 
> >   tbl_summary(by = trt)
> > 
> > tbl_stack(list(tbl_A, tbl_B), group_header = c("**first table**", "**second table**"))
> > ```
> 
> This is a fantastic suggestion, @jalavery ! Would you be interested in making the update? It would require an update to `as_gt()`. I've never tried to make this work with a group header, but expect it is possible with {gt}?
> 

Sure! I may need some guidance but happy to work on it. 

> > 2 - If passing a named list to tbl_stack, could the group_header argument automatically populate with the names from the list?
> > I don't have a sense of how involved either of these updates are, but wanted to mention them as potentially useful features. If not on the priority list for right now, I can go ahead and complete and approve the rest of the review.
> 
> Can we think on this one more, discuss, and perhaps update in a future pull request? How would the users turn off the group headers if we auto populated with the names from the list?

That's a great point - in thinking about it a little more, the following provides a workable solution to what I was thinking of: 

```
# try as a named list
tbl_list <- list("First table" = tbl_A,
     "Second table" = tbl_B)

tbl_stack(tbl_list, group_header = names(tbl_list))
```

**Comment by ddsjoberg** [comment]
Great! @jalavery 

If you get code to get a bold group header in a regular gt table, e.g. `trial %>% group_by(trt) %>% gt()`, then we can work together on getting it working in `as_gt()`?

**Comment by ddsjoberg** [comment]
Thinking about how this could generalize to other output formats....Below is what happens when we use flextable output...

The solution may be that we need to add arguments `group_bold=` and `group_italic=` so we can pass the instructions to other methods.  Anyway, let's start with gt, and go from there!

```r
tbl_stack(list(tbl_A, tbl_B), group_header = c("**first table**", "**second table**")) %>% bold_labels() %>% as_flextable()
```

image

And, I am just now seeing that there is an error with kable and kableExtra outputs :| 

```r
tbl_stack(list(tbl_A, tbl_B), group_header = c("**first table**", "**second table**")) %>% bold_labels() %>% as_kable_extra()
tbl_stack(list(tbl_A, tbl_B), group_header = c("**first table**", "**second table**")) %>% bold_labels() %>% as_kable()
```

**Pull request merged**
