### PR TITLE
Adding `digits=` argument to `tbl_cross()`

### LINKED ISSUE #1044: Adding sum as an officially supported statistic for continuous variables
Hi @ddsjoberg 

It is already possible to use `"{sum}"` as a statistic displayed by `tbl_summary()`.

However, it could be relevant to consider it as a supported statistic, i.e. mentioned in the help file but more importantly being defined in `stat_label_match()`  allowing to associate a stat label and to translate it.

### LINKED ISSUE #1046: Feature request: add a `digits` argument to `tbl_cross()`
Hi @ddsjoberg 

`tbl_cross()` does not have a `digits` arguments. Therefore, the only to customize the number of displayed digits is to change the current theme.

It should be easy to add a `digits` argument to `tbl_cross()` and to pass it internally to `tbl_summary()`.

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Added `digits=` argument to `tbl_cross()`. (#1046)
* Also documented `sum()` in `tbl_summary()`

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #1046
closes #1044

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@larmarange could you take a quick look at these updates?

**Review by larmarange — CHANGES_REQUESTED** [review]
Thanks a lot. This is great.

If I'm right:

- sum should also be mentioned in `tbl_svysummary()` documentation https://github.com/ddsjoberg/gtsummary/blob/63290a512ba9bda6e6b089aacaff46460a3a5799/R/tbl_svysummary.R#L31
- should sum be added to https://github.com/ddsjoberg/gtsummary/blob/master/data-raw/gtsummary_translated.xlsx?

**Comment by ddsjoberg** [comment]
> * sum should also be mentioned in `tbl_svysummary()` documentation 

Sum is already listed there (i think added by you!) 👯 

> * should sum be added to https://github.com/ddsjoberg/gtsummary/blob/master/data-raw/gtsummary_translated.xlsx?

Good point! I added the translations, and added sum to the lookup table for title case/translations.

**Comment by ddsjoberg** [comment]
@larmarange thanks for the helpful comments. I think this is ready for review again (I also increased the min version for broom.helpers)

**Review by larmarange — APPROVED** [review]

**Comment by larmarange** [comment]
This is good for me. Thanks a lot

**Comment by ddsjoberg** [comment]
@larmarange thanks for the review, and pointing out this gap in functionality!

**Pull request merged**
