### PR TITLE
#81 tbl merge ref group

### PR DESCRIPTION
**Pull request by ddsjoberg**
Fixes for issue #81 

@michaelcurry1123 I think this should resolve the issue.

There could still be sorting issues when merging on categorical variables that do not match. But, I think this is good enough for now.  Would you mind doing a review before we merge?

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Oy, thinking about this overnight....should I make the updates now to ensure proper sorting in the merge?  There are no issues if the first model listed includes all levels, but if subsequent models include unobserved levels AND that variable is not listed last, the level will be presented out of order.

**Comment by michaelcurry1123** [comment]
@ddsjoberg  sorry I missed these updates, I was out of town for a long weekend. At what point does the table sort? In your above example what if you switched the order of the models- what would happen?

**Comment by ddsjoberg** [comment]
When listing the model with unobserved levels first, you get:
```
library(gtsummary)
library(survival)

t1 <-
  glm(
    response ~  grade + age, 
    trial %>% dplyr::filter(grade != "I"), 
    family = binomial
  ) %>%
  tbl_regression(
    label = list(trt = "Treatment", grade = "Grade", age = "Age"),
    exponentiate = TRUE
  )

t2 <-
  coxph(
    Surv(ttdeath, death) ~ grade + age, 
    trial
  ) %>%
  tbl_regression(
    label = list(trt = "Treatment", grade = "Grade", age = "Age"),
    exponentiate = TRUE
  )

tbl_merge(
  tbls = list(t1, t2),
  tab_spanner = c("Tumor Response", "Time to Death")
)
```
image


Listing the model will all levels first gives
```
tbl_merge(
  tbls = list(t2, t1),
  tab_spanner = c("Time to Death", "Tumor Response")
)
```
image

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I think it should be merged to deal with the sorting :(. Would turning the variables into factors help (a total guess)?

**Comment by ddsjoberg** [comment]
@michaelcurry1123 you're right.  I can get the levels to present together within a variable, but sorting them properly will be an issue.  All of the terms that come out of a model are character (even if they started as a factor), so we'll just be left with the default ordering after the merge....unless you can think of a way around it?

```
library(tidyverse)
tibble(grade = c("II", "III")) %>%
  full_join(
    tibble(grade = c("I", "II", "III"))
  )
#> Joining, by = "grade"
#> # A tibble: 3 x 1
#>   grade
#>   <chr>
#> 1 II   
#> 2 III  
#> 3 I
Created on 2019-04-24 by the reprex package (v0.2.1)
```

**Comment by ddsjoberg** [comment]
Oy, little setback.  Turns out the original factor levels are NOT retained in `model.frame()`.  In the example below, all the `grade == "I"` were omitted from the model, but when we take a look at the levels there are no longer at `grade == "I"`.  This means that there isn't a way to sort factors properly.   

image

We can still ensure that unobserved levels are grouped within the same variable, but the unobserved levels will be placed at the bottom of the list and not necessarily in the "correct" order.

**Comment by ddsjoberg** [comment]
OK, this is what I've settled on.  Ordering is not guaranteed to be the correct order, but at least levels from the same variable will be presented together.

@michaelcurry1123 this is ready for review. 

```
library(survival)
library(gtsummary)
glm(response ~ grade + age, 
    trial %>% dplyr::filter(grade != "I"), 
    family = binomial) %>%
  model.frame() %>%
  purrr::pluck("grade")

t1 <-
  glm(response ~ grade + age, 
      trial %>% dplyr::filter(grade != "I"), 
      family = binomial) %>%
  tbl_regression(
    label = list(trt = "Treatment", grade = "Grade", age = "Age"),
    exponentiate = TRUE
  )
t2 <-
  coxph(Surv(ttdeath, death) ~ trt + grade + age, trial) %>%
  tbl_regression(
    label = list(trt = "Treatment", grade = "Grade", age = "Age"),
    exponentiate = TRUE
  )
tbl_merge_ex <-
  tbl_merge(
    tbls = list(t1, t2),
    tab_spanner = c("Tumor Response", "Time to Death")
  )
tbl_merge_ex
```

image

**Comment by michaelcurry1123** [comment]
I am getting an interesting error in the example below I removed `trt` from the second model but can't merge the two models together when it is not included. When it is included I can merge them together. 

```
t1 <-
  glm(response ~ grade + age + trt, 
      trial %>% dplyr::filter(grade != "I"), 
      family = binomial) %>%
  tbl_regression(
    label = list(trt = "Treatment", grade = "Grade", age = "Age"),
    exponentiate = TRUE
  )
t2 <-
  coxph(Surv(ttdeath, death) ~  grade + age  , trial) %>%
  tbl_regression(
    label = list( grade = "Grade", age = "Age"),
    exponentiate = TRUE
  )
tbl_merge_ex <-
  tbl_merge(
    tbls = list(t1, t2),
    tab_spanner = c("Tumor Response", "Time to Death")
  )
```

> Error in UseMethod("tbl_vars") : 
>   no applicable method for 'tbl_vars' applied to an object of class "NULL"

**Comment by ddsjoberg** [comment]
ahh, that makes sense.  i had written some custom code the opposite situation, but neglected this one!

**Pull request merged**
