### PR TITLE
Improving messaging in `tbl_stack()` and `modify_*()` functions

### LINKED ISSUE #613: `tbl_stack()` messaging improvements
When two or more gtsummary tables are stacked we retain headers, spanning header, and footnotes from the first table.  

If there are differences in any of these attributes, we should print a message that we're keeping from the first.

### LINKED ISSUE #687: Improve error messaging when no variables selected in `modify_*()`
See example of poor error messaging here:
https://stackoverflow.com/questions/64469429/spanning-header-for-gtsummary-regression-table/64469994#64469994

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- In `tbl_stack()`, the attributes from the first table passed take precedent over the others'. While the documentation is clear about this, multiple users have been confused by this behavior.  We have added messaging indicating if any column headers, footnotes, or spanning headers were changed in the stacking process. closes #613
image

- In the `modfiy_*()` functions, if users did not select any columns, they encountered an error. Now, if no columns are selected, instructions are printed for how to correctly select columns in a gtsummary table. Moreover, if no columns are selected, the gtsummary object is now returned unaltered. closes #687
image

- The `add_glance_source_note()` function has been generalized so users may pass any glance function. Previously, `broom::glance()` was being used with no option to change it.
--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN=true)` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [x] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR. Please use "Suash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@jalavery hey hey!

Would you like to review this pull request? ☺️

**Comment by jalavery** [comment]
> @jalavery hey hey!
> 
> Would you like to review this pull request? ☺️

happy to!

**Comment by ddsjoberg** [comment]
@jalavery great! In particular, what do you think of the messaging?  For example, for `tbl_stack()`, is it too much information coming at the user? Would it be better to print a simple message when there are differences that the attributes from the first table are being used?

**Review by jalavery — COMMENTED** [review]
I think that the `tbl_stack` info is a bit too much, I found it a little confusing to sort through what it was trying to tell me. I think it would be helpful enough to use only the first line of the message ("When tables are stacked, attributes from the first table are used."). 

I love the update to the `modify` functions, I can see that being super helpful!

I'm less familiar with glance functions but it sounds like the update was made so that a user can define their own glance function and `add_glance_source_note` will take that information. I wasn't sure how to test since I've never written a glance function, but am happy to test if you have a user-defined glance function that I can play around with!

**Comment by ddsjoberg** [comment]
@jalavery thank you so much for the comments! Sorry for the delay in responding here.

> I think that the `tbl_stack` info is a bit too much, I found it a little confusing to sort through what it was trying to tell me. I think it would be helpful enough to use only the first line of the message ("When tables are stacked, attributes from the first table are used.").

Good point, I updated to just keep the first part of the message

> I love the update to the `modify` functions, I can see that being super helpful!
👍 

> I'm less familiar with glance functions but it sounds like the update was made so that a user can define their own glance function and `add_glance_source_note` will take that information. I wasn't sure how to test since I've never written a glance function, but am happy to test if you have a user-defined glance function that I can play around with!

Most glance functions are saved in the broom package, but some are exported from the original package...this just allows the user use those if they need.

**Review by jalavery — APPROVED** [review]

**Pull request merged**
