### PR TITLE
haven_labelled messaging for tbl_summary/tbl_svysummary

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Added a message to users if they pass columns with class `"haven_labelled"` to either `tbl_summary()` or `tbl_svysummary()` (#805)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #805 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@larmarange what do you think of this messaging?

**Comment by larmarange** [comment]
Dear @ddsjoberg 

I read the proposed message. Just note sure about `"Failure to convert may have unintended consequences."`. I think it would be better to say how the variable have been considered by `tbl_summary()` by default (i.e. categorical or continuous).

I just installed to the dev version of gtsummary for some tests and I have some issues for labelled numeric vectors.

``` r
library(gtsummary)
library(labelled)

df <- dplyr::tibble(
  v1 = c("m", "f", "f", "m"),
  v2 = c(1, 2, 1, 2)
) %>%
  set_value_labels(
    v1 = c(female = "f", male = "m"),
    v2 = c(yes = 1, no = 2)
  )

df %>%
  select(v1) %>%
  tbl_summary()
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
```
<div id="ehvuklzwrj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 4</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">v1</td>
      <td class="gt_row gt_center"></td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">f</td>
      <td class="gt_row gt_center">2 (50%)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">m</td>
      <td class="gt_row gt_center">2 (50%)</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          n (%)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>

df %>%
  select(v2) %>%
  tbl_summary(type = v2 ~ "categorical")
#> Error: Unable to determine a summary type!
#> 
#> Assign summary types for variables 'v2' (e.g. 'continuous', 'categorical', or
#> 'continuous'). Specify the summary type using the `type=` argument. For example,
#> `type = list(c(v2) ~ "categorical")`

df %>%
  select(v2) %>%
  tbl_summary(type = v2 ~ "continuous")
#> Error: Unable to determine a summary type!
#> 
#> Assign summary types for variables 'v2' (e.g. 'continuous', 'categorical', or
#> 'continuous'). Specify the summary type using the `type=` argument. For example,
#> `type = list(c(v2) ~ "categorical")`

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

There is a bug to fix because it is not possible to specify the type.

If I may:

- I would suggest that by default `tbl_summary` assign a value "categorical" or "continuous" based on the `unclass()` version of the labelled vector, i.e. categorical for labelled character and continuous for labelled double or labelled integer. It should fix the previous bug. It is also meaningful because this is the underlying version of the untransformed vector.
- In your message, indicate how these variables were categorized by `tbl_summary()`

Therefore, the full message woulb be:

```
Columns with class {.field haven_labelled} were detected.
This is an intermediate datastructure not meant for analysis.
By default, {liste of vars} have been categorised as continuous and {list of vars} as categorical.
Defined value labels are not taken into account by tbl_summary()
It is strongly recommended to unclass such variables or to convert them into factors before using tbl_summary.
You can use {.code {cnvt_funs}}.
cli::cli_ul(hyperlinks)
```

**Comment by ddsjoberg** [comment]
Thanks @larmarange !

1. Oy, thank you for pointing out the error. Reverted to the code to what it was before I f*cked it up trying to save some computation time 😭 
2. We use the `inherits()` function to assign type, which I think, works out to be the same as assigning type by the `unclass()` class. For example, in your example, the variable is both haven_labelled and character, so the type is defined as categorical based on its character class. For the `v2` variable, I have added class double as a base numeric type, so that will default to continuous (most of the time...). Here is the updated language:

image

**Comment by larmarange** [comment]
Thanks @ddsjoberg

**Pull request merged**
