### PR TITLE
tbl_summary() calculation of number NA

### LINKED ISSUE #648: Clean up the tidyselect functions
I understand rlang, environments, and tidyselect much better than I did when I wrote `tidyselect_to_list()`, `var_input_to_string()`, and `tidyselect_to_string()`

1. Should this re-write only occur after the `vars()` notation is fully deprecated? This could take a year or more.
1. Remember that `vars()` is the same as `quos()`. If the `vars()` fn is detected, all we likely need to do is bang-bang it, e.g. `!!vars(...)`

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- `tbl_summary()` calculation of NA counts
    - The counts of NA were being calculated twice!
    - About 6 months ago, we began returning other stats for each of the variables, such as the number of missing, non-missing values.
    - We are now taking advantage of those previously calculated statistics, rather than recalculating the number of missing.

**If there is an GitHub issue associated with this pull request, please provide link.**

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN=true)` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
The selecting updates are no longer needed....the selecting functions have been migrated to broom.helpers.

Need to open a new PR with the missing tabulation udpate

**Comment by ddsjoberg** [comment]
hey @michaelcurry1123 !  this one is ready for review again :)

**Comment by michaelcurry1123** [comment]
is there an issue associated with the pull request ?

**Comment by ddsjoberg** [comment]
@michaelcurry1123 I don't think this one had an issue associated

**Review by michaelcurry1123 — APPROVED** [review]

**Comment by michaelcurry1123** [comment]
@ddsjoberg  so I might have prematurely approved this. when I ran the check on my computer I got a few warnings:
checking Rd metadata ... WARNING
  Rd files with duplicated alias 'all_character':
    'deprecated.Rd' 'select_helpers.Rd'
  Rd files with duplicated alias 'all_double':
    'deprecated.Rd' 'select_helpers.Rd'
  Rd files with duplicated alias 'all_factor':
    'deprecated.Rd' 'select_helpers.Rd'
  Rd files with duplicated alias 'all_integer':
    'deprecated.Rd' 'select_helpers.Rd'
  Rd files with duplicated alias 'all_logical':
    'deprecated.Rd' 'select_helpers.Rd'
  Rd files with duplicated alias 'all_numeric':
    'deprecated.Rd' 'select_helpers.Rd'



> checking R code for possible problems ... NOTE
  all_character: no visible binding for global variable 'data_env'
  all_double: no visible binding for global variable 'data_env'
  all_factor: no visible binding for global variable 'data_env'
  all_integer: no visible binding for global variable 'data_env'
  all_logical: no visible binding for global variable 'data_env'
  all_numeric: no visible binding for global variable 'data_env'
  Undefined global functions or variables:
    data_env

**Pull request merged**
