### PR TITLE
New function `add_vif()`

### LINKED ISSUE #717: Add VIFs for regression tables
Hello, guys!

Great work with the package!

I am missing an option to report VIFs of all variables inside a tbl_regression() and also in a tbl_merge().

I went through the whole documentation and searched in Issues and could not find a function. Am I missing anything?

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
 * Added new function `add_vif()` that adds the variance inflation factor or the generalized VIF to a `tbl_regression()` tables. (#717 )
 (The line above can be pasted into NEWS.md when PR is approved, just before it is merged.)

closes #717

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@larmarange can you review this pull request?

**Comment by larmarange** [comment]
> @larmarange can you review this pull request?

Hi. I'm currently on annual leave. If it's not too urgent, I will take time to review it

**Comment by larmarange** [comment]
Two quick comments. Maybe the column header should be equal to the displayed indicator, i.e. VIF or GVIF or adjusted GVIF.

Should the function add a footnote with the detailed name of the acronyms?

Should we allow to pass "adjusted GVIF" to statistic as an addition option, easier to write than GVIF^{1/(2\times df)}?

**Comment by ddsjoberg** [comment]
> > @larmarange can you review this pull request?
> 
> Hi. I'm currently on annual leave. If it's not too urgent, I will take time to review it

No rush at all! Thank you and happy holidays!

**Comment by larmarange** [comment]
Dear @ddsjoberg 

I'm back from holidays and I checked the PR today. I committed some proposals (up to you to keep it or to remove it).

- I propose to allow to display several statistics (i.e. allowing `add_vif(c("GVIF", "aGVIF", "df"))`) to add several columns in one command.
- By default, when there is a categorical term, I suggest displaying both GVIF and aGVIF (to sensibilize the user that there is two stats). Do you think that "df" (degrees of freedom) should also be displayed by default? It will be up to the user to decide what to hide.
- I suggest that `add_vif()` also generates footnotes with the definition of VIF, GVIF, etc.

**Comment by larmarange** [comment]
``` r
library(gtsummary)
lm(age ~ marker + grade, trial) %>%
  tbl_regression() %>%
  add_vif() 
```
image

**Comment by ddsjoberg** [comment]
@larmarange welcome back! I hope you had a great holiday!

all your suggests sounds great. I made a small edit. In all other gtsummary tables, we coalesce all abbreviations to a single footnote, so I've done that for GVIF/VIF.  I changed the styling function for df to round to the nearest integer.  `estimate_fun=` still controls how the VIFs are formatted.

Do you think the function is good to go?

**Comment by larmarange** [comment]
Thanks a lot. Sounds good to me.

Btw, happy new year

**Comment by storopoli** [comment]
Nice! Great job! Will it be included in the next version (1.3.7)?

**Comment by ddsjoberg** [comment]
Yeah,it'll be in the next release...which I think will be 1.4.0 (depending on how some larger changes go!)

**Pull request merged**
