### PR TITLE
Adding `add_p.tbl_continuous()` method

### LINKED ISSUE #1023: Feature request: An `add_p.tbl_continuous` method for summarizing a continuous variable
**Is your feature request related to a problem? Please describe.**
I often want to summarize and compare a given continuous variable (e.g. a biomarker) across a set of other variables. `tbl_continuous()` gives me a beautiful summary. It would be great to also have a statistical comparison readily available. 

**Describe the solution you'd like**
I think an `add_p()` method available for this class would be great. Wilcoxan rank sum seems a natural default test when there are two groups to compare, and perhaps kruskal-wallis could be used for more groups.

**Describe alternatives you've considered**
A custom function worked previously when `tbl_continuous()` was still of class `tbl_summary` but it no longer works now that it is its own class (although I totally could be coding this wrong):

``` r
library(gtsummary)
library(tidyverse)

add_p_test_kruskal2 <- function(data, variable, by, tbl, ...) {
  
  sum_var <- tbl$inputs$variable
  
  stats::kruskal.test(data[[sum_var]], as.factor(data[[variable]])) %>%
    broom::tidy() %>% select(p.value)
  
}

trial %>%
  select(age, response, grade) %>%
  tbl_continuous(variable = age) %>% 
  add_stat(fns = everything() ~ add_p_test_kruskal2) 

#> Error: Argument `x=` must be of class 'tbl_summary' or 'tbl_svysummary'
```
<sup>Created on 2021-11-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Even when it worked, I was a bit confused by the fact that `variable` means a different thing in the `tbl_continuous` context.

(side note: it would also be cool to easily compare continuous by a bunch of other continuous, but not sure if there is a natural default way to display this, and it may be outside the scope of summary tables anyway)

Thank you!!

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**

- Added a `add_p.tbl_continuous()` method for adding p-values to `tbl_continuous()` tables. (#1023)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #1023

There is still opportunity to add more methods. But I feel like those can be added another time.

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [x] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [x] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by karissawhiting** [comment]
This looks great so far! Have you considered about adding `tbl_continuous()` to the vignettes somewhere? Maybe below the cross tables section in `tbl_summary()`?

**Comment by karissawhiting** [comment]
Can you use a custom `add_p()` test for this class?

**Comment by ddsjoberg** [comment]
> Can you use a custom `add_p()` test for this class?

Yep!

**Comment by ddsjoberg** [comment]
> This looks great so far! Have you considered about adding `tbl_continuous()` to the vignettes somewhere? Maybe below the cross tables section in `tbl_summary()`?
> Update: I see it in the gallery which looks good! That may be sufficient?

Yeah I think the gallery is good enough for now!

**Comment by ddsjoberg** [comment]
@karissawhiting ! thank you so much for the review!!!

**Comment by karissawhiting** [comment]
> > Can you use a custom `add_p()` test for this class?
> 
> Yep! There is some documentation on this in the `tests.R` help file

Custom p works like a char! documentation on it looks good to me.

Thanks for adding this method

**Review by karissawhiting — COMMENTED** [review]
Looks great!

**Pull request merged**
