### PR TITLE
146 tidyselect

### PR DESCRIPTION
**Pull request by ddsjoberg**
The selector functions are ready!  `all_numeric()`, `all_double()`, `all_integer()`, `all_logical()`, `all_character()`, `all_continuous()`, `all_categorical(dichotomous = TRUE)`, and `all_dichotomous()`.  We can also use all of the {tidyselect} functions, as well as `vars()` from {dplyr}.

This is a pretty big change.  Can you do a pretty thorough review?  I think everything should be good to go.  One thing that should probably be added is a brief explanation of the select functions.  Perhaps a vignette showing how to use them, and link to the vignette in the help files of functions that use them?

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Issue #146 lists each of the updates made in the package

**Comment by ddsjoberg** [comment]
Are there any other selectors that we need?

**Comment by ddsjoberg** [comment]
@karissawhiting when you build the package on your mac, do you get these warning messages?

image

I can't figure out how to get rid of them, but after some searching it may be a Windows thing

**Comment by karissawhiting** [comment]
@ddsjoberg I am not getting those warning messages building on mac.

**Comment by ddsjoberg** [comment]
@karissawhiting ok thanks!  i wish i weren't seeing them, but i guess it's ok :)

**Comment by karissawhiting** [comment]
This functionality is great! 

A note about the new formula syntax. When I use the old syntax: 

```r 
trial %>%
    dplyr::select(age, response, grade) %>%
    tbl_summary(statistic = list(age = "Median {median}"))
```
I am not getting a deprecation message. Also, when I use the old and new syntax together (probably rare that this will happen), the new formula syntax part is ignored.

Example:

```r
iris %>%
  tbl_summary(statistic = list(all_continuous() ~ "{median}", 
                               "Sepal.Length" = "{mean}"))
```

ignores `all_continuous() ~ "{median}"`, but respects ` "Sepal.Length" = "{mean}"`.

**Comment by ddsjoberg** [comment]
Thank you for the thorough review!!!!

I looked into it, and I was using the incorrect deprecation function (one that only displays the message when the code is called from the global environment).  Updated the code to display the message accurately.

For the second point when the old a new method is mixed...the code checks is the passed list has names (the old syntax).  If there are names it uses the old syntax.
image
The list passed in the example does have names and only uses the named pieces.  I could add another check that the names are all non-empty strings...but I am leaning toward not adding checks for the old syntax.  What do you think?

**Comment by ddsjoberg** [comment]
OK!  Thank you so much for the review.  The deprecation message has been updated (along with some documentation updates, which led to so many documentation files being updated).

**Comment by ddsjoberg** [comment]
@karissawhiting @margarethannum ready for another lookie if you can :)

**Comment by ddsjoberg** [comment]
@margarethannum that's a great update!  It's now included in the PR branch :100:

**Comment by margarethannum** [comment]
I have one last suggestion which is more philosophical, and may impose too much style on the user. 

BUT to highlight some of the usability of tidyselectors (in both {gt} and {gtsummary}, would you consider, as part of this update, renaming the pathology variables "stage" and "grade"  as "path_stage" and "path_grade" as part of the workflow I suggested above? Then we can highlight really using something like `starts_with("path")`. To my above selection we can add something cool from the {gt} package: 

```
trial %>%
  dplyr::select(trt, response, age,  path_stage = stage, marker, path_grade = grade) %>%
  tbl_summary(
    by = "trt",
    type = list(c("response", "grade") ~ "categorical"), # select by variables in a vector
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{p}%") # select by summary type/attribute
  ) %>%
  add_p(test = list(contains("response") ~ "fisher.test", # select using functions in tidyselect
                    all_continuous() ~ "t.test")) %>%
  as_gt() %>%
  tab_row_group(
     group = "Pathology",
rows = starts_with("path"))


```

- I think I need to fix above code a little but you get the idea?

**Comment by ddsjoberg** [comment]
I like that a lot for illustrating the {tidyselect} functions.  The only reason i am hesitant is that the variables names are now colloquial and understood by everyone, and the update is slightly less understandable (and I am feeling some {gtsummary} fatigue!).  We could change the example, maybe?  Do you know of any other data sets in base R (or survival, or gt, or any other package that is loaded with gtsummary) with variables that have common prefix?

**Pull request merged**
