### PR TITLE
Add as_huxtable()

### PR DESCRIPTION
**Pull request by hughjonesd**
**What changes are proposed in this pull request?**

This adds an as_huxtable() function, similar to as_flextable(), which converts the gtsummary object to a huxtable.

It also adds an internal assert_package() function for politely checking if a package is installed.

This is a very rough first shot, though it passes tests which have been copied wholesale from as_flextable(). In particular, I'd like to improve number alignment and formatting, and header styling, and I haven't yet checked if it is getting row indices right.

**If there is an GitHub issue associated with this pull request, please provide link.**

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch 
- [ ] NEWS.md has been updated under the heading "`# gtsummary (development version)`"?
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] If a new function was added, function included in `pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Excellent! I need to fix that CI ASAP! 🔥 

I'll go ahead and close #478 , work on the CI, and take a look at the PR!

**Comment by ddsjoberg** [comment]
I like to make lists so I don't forget! I'll get started on the CI issues. Do you want add more of those formatting functions before I review, or is that something you're thinking would be added much later?

- [ ] Enable GitHub Actions for older versions of R, dev version, Linux, and Windows. @ddsjoberg 
- [ ] Add {huxtable} to `Suggests:` field in `DESCRIPTION`
- [ ] Include functions for alignment, formatting, and header styling

👏 thank you so much for the PR! :octocat:

**Comment by hughjonesd** [comment]
I could do with your help understanding what the desired formatting is for different cells. I see there are formatting functions within `table_header`. Are those always for numeric data? (What about multiple numbers e.g. confidence intervals?) And is the header always bold, or can it be styled, and if so where does that information reside?

**Comment by ddsjoberg** [comment]
Good point!  I'll read up on the formatting huxtable functions, and get back

**Comment by ddsjoberg** [comment]
Hi @hughjonesd , I was looking at the output options, and I think all we should add is a guideline below the column headers.  What do you think?  Also, I updated the checklist above!

**Comment by hughjonesd** [comment]
Glad to help.

**Pull request merged**
