### PR TITLE
Updates for survey v4.1

### LINKED ISSUE #930: Failure due to survey update
From Thomas Lumley:

> You are listed as the maintainers of one or more of these CRAN packages
 "convey"       "grattan"      "gtsummary"    "hutils"       "iNZightPlots" "iNZightTools" "jstable"     
 "svyPVpack"    "tab"          "tableone"   

> With the forthcoming version 4.1 of the survey package your package has new check errors. I think all these errors are due to the new implementation of svyquantile()

> If you just want to make your package pass check with minimal effort, change "svyquantile" to "oldsvyquantile" if "oldsvyquantile" exists (or require version 4.1 of survey). However, the new implementation is better in a number of ways and you might want to use it instead.

> You can get the current development version of 'survey' from https://r-forge.r-project.org/R/?group_id=1788

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**

* With the release of the survey package v4.1, there was a re-write of `svyquantile()` with breaking changes for our code in `tbl_svysummary()`. The survey package still exports `oldsvyquantile()`, and we're using that function for now.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #930 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
hi @larmarange !

I think we can go ahead and merge this as soon as we're ready to submit to CRAN (mid-July the update to survey should go through). At that point I'll remove the `Additional_repositories:` entry from DESCRIPTION.

Do you know know why the R 3.4 checks are failing? Although i've required a min version of survey 4.1 and this version is not available on R 3.4, somehow it's being installed and therefore failing. If you have a moment, could you take a look? I thought it was perhaps the package archive being restored? But I tried updating the archive name to force a refresh, but that didn't work. 🤷🏼

**Comment by larmarange** [comment]
I guess that the skip _if_not_installed() should be inside each test_that() calls to work .

**Comment by ddsjoberg** [comment]
> I guess that the skip _if_not_installed() should be inside each test_that() calls to work .

thanks for taking a look. I think the issue is that it is installed and therefore none of the skips are registering...but it's an old version that doesn't have the updated functions.  maybe i'll just update to allow for both versions....

**Comment by larmarange** [comment]
and with adding a condition on package version number?

**Pull request merged**
