### PR TITLE
340 documentation website

### PR DESCRIPTION
**Pull request by margarethannum**
**What changes are proposed in this pull request?**

- Modify README and vignette documentation to improve readability
- Add language to help SEO for search terms related to our package functionality ("R programming language", "Table 1", "Summary table" etc)
- Add cross-linking across the site
- Updated README images to build differently for website vs GitHub markdown
- Added simplistic table 1 to README
- Added gifs to README to demonstrate `tbl_summary()`, `tbl_regression()`, and `tbl_merge()` functionality
- Created "style" family of functions
- Created `inline_text()` tutorial and removed that information from the other tutorials. 

**If there is an GitHub issue associated with this pull request, please provide link.**
#340 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch 
- [x] NEWS.md has been updated under the heading "`# gtsummary (development version)`"?
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] If a new function was added, function included in `pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. 
- [x] Update `gt_sha` in `data-raw/gt_sha.R` AND run the file.
- [x] R CMD Check runs without errors, warnings, and notes
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by margarethannum** [comment]
@ddsjoberg @karissawhiting Can you look through the documentation updates, especially the README? Might be easiest to view it in it's rendered form by either running `pkgdown::build_site()` or viewing the README on my branch https://github.com/margarethannum/gtsummary/tree/340_documentation_website

1. Do we like the gifs on the README? Should they be moved to a "demonstration" page instead if they take up too much room?
2. I intended to shorten the README but it got longer... I think it flows alright but please let me know what suggestions you have to improve things. 
3. Dan: with the `gtsave()` on the README I somehow made a "README_files" folder. If you can recall more how you saved those files automatically originally let me know if I need to change something in how I implemented this!

**Comment by ddsjoberg** [comment]
@margarethannum I have no idea where the README_files folder came from.  When I knit `README.Rmd` file, I get these files saved to the `man\figures\` folders:
image

At the top of the `README.Rmd` file we have this options chunk that specifies where we save the images from README.  I don't know much about this, but it does seem to be working as expected on my machine, right?

```r
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

**Comment by margarethannum** [comment]
Updated with revisions. 
-changed GIFs in README and other small README changes
-updated packages on my machine and ran use_tidy_versions and description
-updated description of show_single_row argument
-replaced "binary" with "dichotomous" throughout package
-fixed table of variables in trial in pkgdown (need extra indents under a bulleted list)

**Comment by margarethannum** [comment]
Pushed some "final" (cross fingers) documentation updates. 

* Updated NEWS.md
* Added `inline_text()` tutorial, removed that information from the other tutorials. 
* Spell check etc and rebuilt package. 
* Removed README_files folder that was part of some prior build version when I was testing way to build README figures for GitHub vs pkgdown.

Note there is a warning about "Duplicate identifier 'inline_text' at line 99 column 1" which I don't know how to solve, it is getting thrown at a place that is literally using code from the previous version of the site (just moved it to the new `inline_text()` vignette).  This warning shows up only during `pkgdown::build_site()`. R CMD checks run with 0 errors, warnings, or notes. 

@ddsjoberg please review the `inline_ and rebuild the package to take care of the contributor list, then I think we may be good to go!

**Pull request merged**
