### PR TITLE
Bold/Italicize Levels/Labels Methods for `tbl_cross`

### LINKED ISSUE #442: Allow label/level bolding and italicizing to work on cols in tbl_cross()
Functions to bold and italicize levels/labels only work on row variables and not column variables in `tbl_cross()`. 

Example:
```r
trial %>% tbl_cross(trt, response) %>% italicize_levels()
``` 
This may require making these formatting functions into method functions.

### PR DESCRIPTION
**Pull request by karissawhiting**
**What changes are proposed in this pull request?**

This PR turns `bold_labels()`, `bold_levels()`, `italicize_labels()`, `italicize_levels()` into method functions so they can work better on `tbl_cross` objects. 

A few notes:
- By default, `tbl_cross()` already bolds labels. We could change the default to not bold to match `tbl_summmary()` but to avoid changing existing defaults (as discussed) I added a warning when you try to `bold_labels(tbl_cross)`. 
- I did a cursory check of print engines and wanted to confirm the following: 
     - `as_gt()`/`as_kable_extra()`/`as_hux_table()` look fine in HTML . `as_flex_table()` doesn't italicized or bold headers (but I think this is known behavior)
     - `as_kable_extra()`/`as_hux_table()` look fine in PDF . `as_flex_table()` doesn't italicize or bold headers and `as_gt()` doesn't italicize or bold the body (but I think this is known behavior). Couldn't check `as_kable()` due to some systems issues I'm having, sorry!.
- If a user has already applied `modify_table_header()` on `tbl_cross`, should we throw a warning that some of their modifications may be overwritten?
- Please let me know if there is a better way I should document these now that they are methods!

**If there is an GitHub issue associated with this pull request, please provide link.**

closes #442 

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [x] Ensure all package dependencies are installed by running `renv::install()`
- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
hey hey @karissawhiting ! reviewing the updates here: do you think everything would be more clear straightforward if we just removed the default bolding in `tbl_cross()`? It seems that would just make everything easier?

**Comment by karissawhiting** [comment]
It may be easier and more consistent behavior if you think the change in default settings wouldn't affect users too much?

**Comment by ddsjoberg** [comment]
hey hey @karissawhiting ! the updates look amazing, thank you for doing this

I made a few minor changes on review
- In `add_p.tbl_cross()`, the column header is no longer bold by default to be consistent with the output from `tbl_cross()`
- Removed the header from the label column...just a blank space now.
- Re-ordered the functions in the help file
- When the user runs `bold_labels()` the p-value column is now bold as well (what do you think of this?)
- Removed `.assert_class(x, "gtsummary")` from the gtsummary methods, since the object must now be gtsummary to be dispatched to them method.
- Added `bold_labels()` to the examples in `tbl_cross()` and updated the images in the help file
- In the pkgdown yaml, I replaced the listing of every bold/italicize method with a single `bold_italicize_labels_levels` (the Rd filename

Can you take a look at my changes? If all good, then I think we're ready to finish the checklist and merge!

**Comment by karissawhiting** [comment]
@ddsjoberg changes look great to me!

**Pull request merged**
