### PR TITLE
Update tbl_survfit.R

### LINKED ISSUE #608: tbl_survfit bug in dev version
The dev version has a bug in `tbl_survfit()`. The code below works in the released version, but not in dev.

```r
library(tidyverse)
library(gtsummary)
library(survival)


tibble(var = c("grade", "trt")) %>%
  mutate(
    formula = map(var, ~str_glue("Surv(ttdeath, death) ~ {.x}") %>% as.formula()),
    survfit = map(formula, ~survfit(.x, data = trial)),
    tbl_survfit = map(survfit, ~tbl_survfit(.x, times = c(12, 24)))
  ) %>%
  pull(tbl_survfit) %>%
  tbl_stack()
```

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
Addressing #608

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #608 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN = TRUE)` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@michaelcurry1123 thank you! Updated!

**Comment by ddsjoberg** [comment]
Well, that is a new bug you found!! Should be fixed with this push! @michaelcurry1123 

I updated the check to look for an equal sign AND for at least one of these `", "`.  

And because this is not perfect parsing, I just added this as a message (not an error).

```r
 # if you have more than one equal sign
          stringr::str_count(tidy$strata[1], pattern = fixed("=")) > 1 &&
          # there are more than one "word" with sep = ", ", then you likely have more than one var
          stringr::str_count(tidy$strata[1], pattern = fixed(", ")) >= 1
```

**Comment by michaelcurry1123** [comment]
Glad we caught it! So with two variables it gives that message and also produces output, which is numerically correct but stylistically not correct. The paring is tough just because the way the survift object creates the strata variable. I think it is good as a message for now. If you are fine with the output of the code below I would be happy to approve the pull request:
```
trial2 <- mutate(trial, 
                 newvar = ifelse(grade == "I", "Grade=I , = ",
                          ifelse(grade == "II","Grade=II , = ","Grade=III , =")),
                 gradetrt = paste(grade , trt, sep = " "))

s1 <- survfit(Surv(ttdeath, death)~ grade+trt, data = trial2)

tbl_survfit(s1, probs = .25)

s1a <- survfit(Surv(ttdeath, death)~gradetrt, data = trial2)

tbl_survfit(s1a, probs = .25)

s2 <- survfit(Surv(ttdeath, death)~newvar, data = trial2)

tbl_survfit(s2, times = 12)
```

**Comment by ddsjoberg** [comment]
Nice! I am fine with the output as it is. It's more of warning in case they run into issues downstream.

Almost there!! YAY thank you!

**Comment by ddsjoberg** [comment]
@michaelcurry1123

**Comment by michaelcurry1123** [comment]
@ddsjoberg  approved, can you merge? I always forget how to do the versioning!

**Pull request merged**
