### PR TITLE
Benchmark4

### PR DESCRIPTION
**Pull request by oranwutang**
**If there is an GitHub issue associated with this pull request, please provide link.**
#802 
  ### **What changes are proposed in this pull request?**

Hi!

I have opened this new pulls request (just because I'm trying to merge from a branch different than the previous one, I don't know if this has (git)sense, tho...)

As I explained you in my last e-mail message (I’m not sure that you have read it) I have adapted my own code to run on a github action, I think that this is working pretty fine.  Results of benchmark are showcased in the /benchmark folder of the respective branch as a github-md document ([see an exmaple here](https://github.com/oranwutang/gtsummary/tree/benchmark4/benchmark )). 

I was surprised that most of the times the “simple” function took more time to run than more complex functions like “big_data”, after some reading I have discovered that it may be due to garbage collection (GC), “simple” function makes a call to GC almost for every iteration! Honestly, I just don’t know why!. It is also true that other times "complex" or "big_data" make more calls to GC than "simple", it seems like a random process, look at the following plot for an example:

garbagecollection

GC in R is a bit tricky thing and there’s not so much information about it over there, so I don’t know why one function calls GC more than other, but it is clear that the more GC required during benchmark, the more that function will last to run. In brief, these benchmarks wont let you compare between functions (simple vs complex vs big_data), on the other hand I do think that it does let you compare the same function among different versions of gtsummary, which, I think, is the final purpose of this workflow.

Additionally, you may notice that I have lowered the number of iterations and the size of ‘big_trial’ as well, that is for sake of lowering the total time that the workflow takes to complete, using your original configuration (big_trial = 1000000 observations and 30 iterations) made the workflow take about 45 minutes to complete. But, this parameters may be modified as per your needs.

I have finally decided to use {microbenchmark} instead of {bench}, just because the former offers an output that is more comfortable for me, but if you think that {bench} should be used I’ll be happy to rewrite the required code.

Please, let me know what you think and if there is any suggestion or something that requires modification, I’ll be glad to keep collaborating with you.

So, I’ll keep awaiting for instructions!

Best regards!

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Review by oranwutang — COMMENTED** [review]
File " .github/workflows/cu" is just a backup, can be deleted. Sorry, I forgot to delete it before PR :S

**Comment by ddsjoberg** [comment]
hey @oranwutang ! this looks great! The approach is perfect. I have a couple of questions

- The `bench` folder can be deleted, right?
- The approach is perfect here for benchmarking. Do you mind if a make edits to check more previous versions?

Thanks!

**Comment by oranwutang** [comment]
Hi @ddsjoberg!

I'm glad you like it!
 
>     * The `bench` folder can be deleted, right?
Yes, it must be deleted.

>     * The approach is perfect here for benchmarking. Do you mind if a make edits to check more previous versions?
Yes, please make all edits you need.

I hope that this PR will improve the development of this great package!

**Comment by ddsjoberg** [comment]
closes #755

**Comment by ddsjoberg** [comment]
Thank you @oranwutang !

In the end I removed the GitHub Actions portion. The commit at the end was causing some weird issues with the other Actions: they are not triggered by the benchmark and so we couldn't see if the regular checks were passing for each pull request.

**Comment by oranwutang** [comment]
Hi Daniel!

Maybe sorting the different actions and putting the benchmark as the last action to run, solves this trouble? 

Here is a post on how to do it:
https://stevenmortimer.com/running-github-actions-sequentially/#an-example

**Pull request merged**
