### PR TITLE
tbl_regression as an S3 function

### LINKED ISSUE #607: Taking into account other contrast in `tbl_regression()`
I was recently exploring a model using `contr.sum`. I was thinking if `tbl_regression()` should take into account or not such contrasts.

Here a quick example:

``` r
library(gtsummary)
mod <- glm(response ~ age + grade, trial, family = binomial(link = "logit"), contrasts = list(grade = contr.sum))
tbl_regression(mod, exponentiate = TRUE)
```

<div id="xinkgtskby" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>OR</strong><sup class="gt_footnote_marks">1</sup>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>p-value</strong>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Age, yrs

</td>

<td class="gt_row gt_center">

1.02

</td>

<td class="gt_row gt_center">

1.00, 1.04

</td>

<td class="gt_row gt_center">

0.10

</td>

</tr>

<tr>

<td class="gt_row gt_left">

grade1

</td>

<td class="gt_row gt_center">

1.05

</td>

<td class="gt_row gt_center">

0.67, 1.62

</td>

<td class="gt_row gt_center">

0.8

</td>

</tr>

<tr>

<td class="gt_row gt_left">

grade2

</td>

<td class="gt_row gt_center">

0.90

</td>

<td class="gt_row gt_center">

0.56, 1.40

</td>

<td class="gt_row gt_center">

0.6

</td>

</tr>

</tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="4">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

OR = Odds Ratio, CI = Confidence Interval
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

<sup>Created on 2020-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I do not know that would be the best representation. For `contr.sum()`, each coefficient represents the difference of each level with the great mean. However, for the last level, the difference with the great mean corresponds to the sum of all coefficients multiplied by -1.

I'm not sure how such models are usually presented in the literature as they are less common that the default `contr.treatment()`.

It is not very urgent but eventually something to consider at some point.

### LINKED ISSUE #636: Integrating broom.helpers in gtsummary
A first version of `broom.helpers` (https://github.com/larmarange/broom.helpers) is now almost finalized and I feel that it's covering all `gtsummary` needs (do not hesitate to tell if it is not the case).

Some considerations for integrating it within `gtsummary`:

- it could be relevant to write an internal `tidy_gtsummary()` function (a clone of `tidy_plus_plus()`) handling specific treatment for `gtsummary`.
- `tidy_add_term_labels()` and `tidy_add_variable_labels()` accept named list but not a list of formulas. The transformation of a list of formulas into a named list should still be handle by  `gtsummary()`
- similarly, `broom.helpers` do not have an equivalent of include (as it could be done with a `dplyr::filter`)
- to save memory, it could be relevant to apply `tidy_detach_model()` at the end of the process, as the is already stored within the gtsummary table
- for consistency of column names, some names are not exactly the same between `broom.helpers` and gtsummary and there are some extra columns. So there is maybe few data manipulation to do in `gtsummary`
- `tidy_add_estimate_to_reference_rows()` is able to manage the issue discussed in #607   the question is open about adding an option for that in `tbl_regression()`  (or if it should be done in a separate function, but in that case, merging issue could arise).

### LINKED ISSUE #637: Standard error instead of CI in tbl_regression?
I get the sense from poking around in documentation there might be a way to do this manually, but I'd like to be able to swap the CI column in the tbl_regression for a standard error column. The journals in my field tend to expect SE instead of CI, and it would be amazing to be able to set something like add_CI = F and add_SE = T.

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- [x] updates the `tbl_regression()` internals to use broom.helpers package THIS IS A BIG CHANGE! (#636, #607)
    - we should now be able to accept ANY wild or horribly named variable
    - the infrastructure sets us up to accept more model types 
- [x] transforms `tbl_regression()` into multiple methods: `tbl_regression.default()`, `tbl_regression.lmer()`, `tbl_regression.glmer()`, `tbl_regression.survreg()`
- [x] allow users to to choose which columns to report with a theme element.  they can choose among the estimate, std error, statistic, ci, and p-value (#637) 
- [x] allow users to include the reference value via a theme element
- [x] update the printers to use the column `reference_row` from broom.helpers (currently changing name to match the prior version)
- [x] update the missing emdash column in `x$table_header` to be missing_reference_row and allow users to change the symbol with a theme element. (#628)

**If there is an GitHub issue associated with this pull request, please provide link.**  
closes #636
closes #637
closes #607

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN = TRUE)` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by larmarange** [comment]
Can't wait to see it. Awesome

**Comment by michaelcurry1123** [comment]
@ddsjoberg  for issue #637 if you run the code in that example the title for the OR is exp(Beta). The same is true if you run a cox model. See example below:

```
glm(response ~ age + grade, trial, family = binomial) %>%
  tbl_regression(exponentiate = TRUE) %>%
  # add standard error, test statistic
  modify_header(
    statistic = "**Statistic**",
    std.error = "**SE**"
  ) %>%
  # hide confidence interval
  modify_table_header(
    column = "ci", 
    hide = TRUE, 
    missing_emdash = NA_character_,
    footnote_abbrev = NA_character_
  )
```

image

**Comment by michaelcurry1123** [comment]
Not sure how much to care about this fringe case but if you have a + sign in the column name (even if the variable has a label) it is removed from the `tbl_regression()` output. No warning/error is generated.

```
trial2 <- trial %>% 
          mutate(`treatment +name` = trt)


mod <- glm(response ~ age + `treatment +name`+ grade, trial2, family = binomial(link = "logit"))
tbl_regression(mod, exponentiate = TRUE)

```

image

**Comment by ddsjoberg** [comment]
@michaelcurry1123 

I am not concerned about that edge case.  I'll report it to broom.helpers just to let him know, though! 🕺 


``` r
library(gtsummary)

trial2 <- 
  trial %>% 
  dplyr::mutate(`treatment +name` = trt)


glm(response ~ age + `treatment +name`+ grade, 
    trial2, 
    family = binomial(link = "logit")) %>%
  broom.helpers::tidy_and_attach() %>%
  broom.helpers::tidy_remove_intercept()
#> # A tibble: 3 x 8
#>   term     variable var_class var_type    estimate std.error statistic p.value
#>   <chr>    <chr>    <chr>     <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 age      age      numeric   continuous   0.0190     0.0114    1.67    0.0952
#> 2 gradeII  grade    factor    categorical -0.161      0.395    -0.406   0.685 
#> 3 gradeIII grade    factor    categorical  0.00767    0.385     0.0199  0.984
```

<sup>Created on 2020-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Following https://github.com/larmarange/broom.helpers/issues/44 it should have been fixed in the development version of broom.helpers

Dear @ddsjoberg, do you see any other issue to fix in broom.helpers, before submitting a new version to CRAN?

**Comment by ddsjoberg** [comment]
@larmarange thanks for updating! Perhaps submit after @michaelcurry1123 has finished the review of this PR? 👋🐻

**Review by michaelcurry1123 — APPROVED** [review]

**Pull request merged**
