### PR TITLE
Mice nnet

### LINKED ISSUE #645: Add `tbl_regression()` for 'mice' and 'nnet::multinom' models
Once PR #606 is merged, add methods for `nnet::multinom()` models and mice models.

Here's an outline of the multinom model. 

```r
#' @export
#' @rdname tbl_regression_methods
tbl_regression.multinom <- function(x, exponentiate = FALSE, conf.level = 0.95, group_header = NULL, ...) {

  inform("Constructing `tbl_regression()` objects for each outcome")
  df_tidy <-
    broom::tidy(x, exponentiate = exponentiate,
                conf.level = conf.level, conf.int = TRUE) %>%
    dplyr::nest_by(.data$y.level) %>%
    rowwise() %>%
    mutate(
      # creating a tidy function that just returns the piece needed of this tidy data frame
      tidy_data = list(function(x, ...) .data$data),
      # running tbl_regression on each piece of the tidy tibble (for each outcome)
      tbl_regression =
        tbl_regression.default(x = x, tidy_fun = .data$tidy_fun, ...) %>%
        list()
    )

  inform("Stacking `tbl_regression()` objects for each outcome using `tbl_stack()`")
  tbl_stack(df_tidy$tbl_regression, group_header = group_header %||% df_tidy$y.level)
}
```

For the mice model, perhaps we can allow the user to pass a model object that we can use if we can't grab the model from the call of `pool()`

Related to #517

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
mice and nnet mutlinomial models can now be used in `tbl_regression()`.
  - PR implements a tidy method for mice (mira) objects. the tidy method performs the `mice::pool()` portion AND the `mice::tidy()` part. The reason for this is that the pooling function removes the model objects, and returns a tibble of the summarized model. We can access one of the underlying models build on one of the imputed sets so we can extract the variable names, contrasts, etc.
  - PR includes a tbl_regression method for nnet multinomial models.  The underlying dataset is one line per level of the outcome per term in the model.  This is not the typical structure.  I added a note indicating the other tbl_regression functions may yield unexpected results.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #645

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN=true)` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@karissawhiting @michaelcurry1123 this one is also available, if you'd like 🍁

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I am up for it

**Comment by ddsjoberg** [comment]
> @ddsjoberg I am up for it

Thanks @michaelcurry1123 ! Would you be able to start with https://github.com/ddsjoberg/gtsummary/pull/685 ?

**Comment by michaelcurry1123** [comment]
@ddsjoberg never been more up for it!

**Comment by ddsjoberg** [comment]
@michaelcurry1123 haha yay!

**Pull request merged**
