### PR TITLE
Adding standard errors of proportions to tbl_svysummary

### LINKED ISSUE #1187: Feature request: Calculate precision estimates for proportions on survey objects
**Is your feature request related to a problem? Please describe.**
When calculating proportions (or percentages) from a survey, there is a standard error associated with that. This should be calculated in the survey package.

**Describe the solution you'd like**
Add the following statistics for categorical variables with suggested name:
- Standard error of the percentage: `p_se`

**Describe alternatives you've considered**
Currently, I do this in the srvyr package and then wrangle data to make a nice table using gt package. No current method directly available in gtsummary.

**Additional context**
Here's a very rough reprex of what output is expected.

``` r
data(api, package = "survey")
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)
library(gtsummary)
library(gt)

# Example from gtsummary documentation
data(api, package = "survey")
tbl_svysummary_ex2 <-
  survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) %>%
  tbl_svysummary(by = "both", include = c(cname))

tbl_svysummary_ex2
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>No</strong>, N = 1,692<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Yes</strong>, N = 4,502<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">cname</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Alameda</td>
<td class="gt_row gt_center">68 (4.0%)</td>
<td class="gt_row gt_center">305 (6.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Fresno</td>
<td class="gt_row gt_center">0 (0%)</td>
<td class="gt_row gt_center">135 (3.0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Kern</td>
<td class="gt_row gt_center">34 (2.0%)</td>
<td class="gt_row gt_center">34 (0.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Los Angeles</td>
<td class="gt_row gt_center">135 (8.0%)</td>
<td class="gt_row gt_center">372 (8.3%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Mendocino</td>
<td class="gt_row gt_center">135 (8.0%)</td>
<td class="gt_row gt_center">0 (0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Merced</td>
<td class="gt_row gt_center">34 (2.0%)</td>
<td class="gt_row gt_center">102 (2.3%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Orange</td>
<td class="gt_row gt_center">102 (6.0%)</td>
<td class="gt_row gt_center">440 (9.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Plumas</td>
<td class="gt_row gt_center">169 (10%)</td>
<td class="gt_row gt_center">135 (3.0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">San Diego</td>
<td class="gt_row gt_center">508 (30%)</td>
<td class="gt_row gt_center">1,354 (30%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">San Joaquin</td>
<td class="gt_row gt_center">372 (22%)</td>
<td class="gt_row gt_center">880 (20%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Santa Clara</td>
<td class="gt_row gt_center">135 (8.0%)</td>
<td class="gt_row gt_center">745 (17%)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">1</sup> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>

```r
# Example with se of p

estlong <- apiclus1 %>%
  srvyr::as_survey_design(id = dnum, weights = pw, fpc = fpc) %>%
  group_by(both, cname) %>%
  summarise(
    p=srvyr::survey_prop(proportion = TRUE),
    .groups="drop"
  ) 

estlong
```
#> # A tibble: 20 x 4
#>    both  cname             p    p_se
#>    <fct> <chr>         <dbl>   <dbl>
#>  1 No    Alameda     0.0400  0.0419 
#>  2 No    Kern        0.0200  0.0214 
#>  3 No    Los Angeles 0.0800  0.0806 
#>  4 No    Mendocino   0.0800  0.0806 
#>  5 No    Merced      0.0200  0.0214 
#>  6 No    Orange      0.0600  0.0617 
#>  7 No    Plumas      0.100   0.0986 
#>  8 No    San Diego   0.300   0.176  
#>  9 No    San Joaquin 0.220   0.187  
#> 10 No    Santa Clara 0.0800  0.0662 
#> 11 Yes   Alameda     0.0677  0.0689 
#> 12 Yes   Fresno      0.0301  0.0318 
#> 13 Yes   Kern        0.00752 0.00810
#> 14 Yes   Los Angeles 0.0827  0.0713 
#> 15 Yes   Merced      0.0226  0.0240 
#> 16 Yes   Orange      0.0977  0.0964 
#> 17 Yes   Plumas      0.0301  0.0318 
#> 18 Yes   San Diego   0.301   0.179  
#> 19 Yes   San Joaquin 0.195   0.171  
#> 20 Yes   Santa Clara 0.165   0.111

```r
# Very rough example but note the standard erros of the p

estwide <-
  estlong %>%
  complete(both, cname) %>%
  replace_na(list(p=0)) %>%
  mutate(
    value=glue::glue("{format(p*100, digits=1)} ({format(p_se*100, digits=1)})")
  ) %>%
  pivot_wider(id_cols=cname, names_from=both, values_from=value) %>%
  gt() %>%
  tab_footnote("% (se)", locations=cells_column_labels(c("No", "Yes")))

estwide
```
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">cname</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">No<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Yes<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Alameda</td>
<td class="gt_row gt_center"> 4.0 ( 4.2)</td>
<td class="gt_row gt_center"> 6.8 ( 6.9)</td></tr>
    <tr><td class="gt_row gt_left">Fresno</td>
<td class="gt_row gt_center"> 0.0 (  NA)</td>
<td class="gt_row gt_center"> 3.0 ( 3.2)</td></tr>
    <tr><td class="gt_row gt_left">Kern</td>
<td class="gt_row gt_center"> 2.0 ( 2.1)</td>
<td class="gt_row gt_center"> 0.8 ( 0.8)</td></tr>
    <tr><td class="gt_row gt_left">Los Angeles</td>
<td class="gt_row gt_center"> 8.0 ( 8.1)</td>
<td class="gt_row gt_center"> 8.3 ( 7.1)</td></tr>
    <tr><td class="gt_row gt_left">Mendocino</td>
<td class="gt_row gt_center"> 8.0 ( 8.1)</td>
<td class="gt_row gt_center"> 0.0 (  NA)</td></tr>
    <tr><td class="gt_row gt_left">Merced</td>
<td class="gt_row gt_center"> 2.0 ( 2.1)</td>
<td class="gt_row gt_center"> 2.3 ( 2.4)</td></tr>
    <tr><td class="gt_row gt_left">Orange</td>
<td class="gt_row gt_center"> 6.0 ( 6.2)</td>
<td class="gt_row gt_center"> 9.8 ( 9.6)</td></tr>
    <tr><td class="gt_row gt_left">Plumas</td>
<td class="gt_row gt_center">10.0 ( 9.9)</td>
<td class="gt_row gt_center"> 3.0 ( 3.2)</td></tr>
    <tr><td class="gt_row gt_left">San Diego</td>
<td class="gt_row gt_center">30.0 (17.6)</td>
<td class="gt_row gt_center">30.1 (17.9)</td></tr>
    <tr><td class="gt_row gt_left">San Joaquin</td>
<td class="gt_row gt_center">22.0 (18.7)</td>
<td class="gt_row gt_center">19.5 (17.1)</td></tr>
    <tr><td class="gt_row gt_left">Santa Clara</td>
<td class="gt_row gt_center"> 8.0 ( 6.6)</td>
<td class="gt_row gt_center">16.5 (11.1)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">1</sup> % (se)</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by szimmer**
Add `p_se` as a statistic for categorical variables in tbl_svysummary. At this time, some more work needs to be done - namely updating the default format for p_se to be percentage and a better footnote, perhaps ("SE (%)")

closes #1187 

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [x] Ensure all package dependencies are installed by running `renv::install()`
- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [x] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [x] Increment the version number using `usethis::use_version(which = "dev")` 
- [x] Run `codemetar::write_codemeta()`
- [x] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Thanks @szimmer ! I added the label for the SE statistic, and the default formatting function for it is going to be `style_sigfig(x, digits = 2)`.

**Comment by szimmer** [comment]
It's now ready for review - I made some changes so that it uses the percent_fun not sigfig format so it has the standard error has the same units as the proportion. I think this would be great for @larmarange to review as he has time.

**Comment by larmarange** [comment]
I'm currently traveling in Africa with limited internet access but will review it by the end of the week

Best regards

**Comment by ddsjoberg** [comment]
@szimmer hello!

it looks there the R CMD Checks are failing. Have you had a chance to run the checks locally? Are you seeing the same errors there?

**Comment by ddsjoberg** [comment]
@szimmer you mentioned that you updated the formatting function for the SE to be `style_percent()`? FYI, for percentages below 0.1 and shown as "<0.1%". I think we should stick with `style_sigfig()`

**Comment by larmarange** [comment]
@szimmer according to the github actions, several tests failed regarding the new code of `tbl_svysummary()`.

Can you try `devtools::test()` on your machine and explore why the tests are failing?

**Comment by szimmer** [comment]
Yes, I was looking but will dig in on Monday.

**Comment by ddsjoberg** [comment]
Hello @szimmer ! How is the pull request coming along? Would it be helpful to jump onto a call this coming week to discuss anything?

**Comment by larmarange** [comment]
I just made a few changes (converting numeric variables to factors when doing a categorical summary and taking into account missing values). It should fix some of the issues. But still, need to verify all checks.

**Comment by larmarange** [comment]
I have made other fixes. Most tests should pass now.

However, there is still a small bug to fix. If there is a `by`, and if `variable` name starts with `"see."`, the code will fail to distinct **p** and **p_se** (cf. this line of code `stat = if_else(str_sub(.data$name, 1, 3) == "se.", "p_se", "p"),  # note: will fail if variable name start with "se."` repeated twice).

We may have to find a better way to deal with that case.

**Comment by larmarange** [comment]
Last comment should be covered by https://github.com/ddsjoberg/gtsummary/pull/1240/commits/f7c478b0414bb97760c61c40c429129b9daefba5

**Comment by larmarange** [comment]
It would be relevant to explore codecov report to identify new tests to add. For example, we should test that all types of percentages (col, row, cell) are correctly computed.

**Comment by ddsjoberg** [comment]
@szimmer @larmarange 

I tried to look into the source of the error, and it's this line that is currently erroring FYI

``` r
survey::svydesign(data = gtsummary::trial, ids = ~1, weights = ~1) |> 
  survey::svymean(~response, design = _)
#>          mean  SE
#> response   NA NaN
```

<sup>Created on 2022-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

These NAs and NaNs should be numbers. Check out line 327 of `tbl_svysummary.R` using the response variable in the trial data set.

**Comment by larmarange** [comment]
The `NA` issue should have been fixed now.

``` r
library(gtsummary)
survey::svydesign(data = gtsummary::trial, ids = ~1, weights = ~1) %>%
  tbl_svysummary() %>%
  as_kable()
```

| **Characteristic**     |    **N = 200**    |
|:-----------------------|:-----------------:|
| Chemotherapy Treatment |                   |
| Drug A                 |     98 (49%)      |
| Drug B                 |     102 (51%)     |
| Age                    |    47 (38, 57)    |
| Unknown                |        11         |
| Marker Level (ng/mL)   | 0.62 (0.21, 1.38) |
| Unknown                |        10         |
| T Stage                |                   |
| T1                     |     53 (26%)      |
| T2                     |     54 (27%)      |
| T3                     |     43 (22%)      |
| T4                     |     50 (25%)      |
| Grade                  |                   |
| I                      |     68 (34%)      |
| II                     |     68 (34%)      |
| III                    |     64 (32%)      |
| Tumor Response         |     61 (32%)      |
| Unknown                |         7         |
| Patient Died           |     112 (56%)     |
| Months to Death/Censor | 22.4 (15.8, 24.0) |

<sup>Created on 2022-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
FYI I updated the name from `p_se` to `p.std.error` matching the `tidy::broom()` names for standard errors

**Review by ddsjoberg — APPROVED** [review]
Hey @larmarange ! I updated the name of the SE of the proportion. Can you do a final check and merge when ready? I've approved the PR so you can merge whenever. Thanks!

**Review by larmarange — APPROVED** [review]

**Comment by larmarange** [comment]
HI @ddsjoberg 

it looks good to me.

There is maybe just a little something in the wording in the document. We are using the expression **standard error of the proportion** and I know that this expression is used in different places. But would it be more accurate to say **standard error of the proportion estimate** or **standard error of the sample proportion**?

**Review by larmarange — APPROVED** [review]

**Pull request merged**
