### PR TITLE
New function `add_difference()`

### LINKED ISSUE #617: Add differences to tables created by tbl_summary()
How to add differences to tbl_summary tables?

`add_difference()`
- differences in means, but how can it be generalized to differences in any statistic?
- differences in rates
- raw vs adjusted differences
- standardized differences

`add_paired_difference()`
- we'd need to reshape the data and calculate the difference
- we can report any summary stat like we do for `tbl_summary(statistic=)`

Do we add new columns for CIs?

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- Added new function `add_difference()`, which adds difference between groups, confidence interval and p-value. (#617)
- Removed `"Statistics presented:"` and `"Statistical tests performed:"` prefixes from the `tbl_summary() %>% add_p()` footnotes.

Additional questions for reviewers: 
1. What do you think of removing the prefixes for the statistics presented and tests performed?  Improvement? Worse?
1. Please review the added documentation `?add_difference()` and `?tests`. How can they be improved?

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #617 

```r
trial %>%
    select(trt, age, marker) %>%
    tbl_summary(by = trt, missing = "no", statistic = everything() ~ "{mean} ({sd})") %>%
    add_difference()
```

image

NOTE: The current setup requires the same formatting function to be applied to the difference and CI. This means that we can't have continuous and binary data summarized in the same table (since they need different formatting; see the help file `?add_difference()` for example).  Ultimately, I would like to update the general structure of a gtsummary object to allow for column (already done) AND row formatting (needs to be implemented).  When that is complete, we can apply different formatting fns based on the type of summary.

**To Do**
Coding:
- [x] Add method for difference between rates, perhaps `prop.test()`?
- [x] Add method for ANCOVA
- [x] Add a method for correlated data. 
- [x]  Add method for standardized differences??
- [ ] Add theme elements 
- [x] Decide how to handle categorical data. Do we require that all categorical variables are dichotomous? I think that seems reasonable. Categorical variables can auto be excluded from `include=`
- [x] Do we add a footnote for the method used?  Where to put it?
- [x] Do we add a `adjust.vars=` argument to `add_difference()` to assist with passing covariate adjustments in ANCOVA and other methods with adjustment?

Documentation:
- [x] Update tests.R with a add_difference section

Unit Testing:
- [x] Add at least one unit test for each method
--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] NEWS.md has been updated with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see NEWS.md for examples).
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] When the branch is ready to be merged into master, increment the version number using `usethis::use_version(which = "dev")`, run `codemetar::write_codemeta()`, approve, and merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by larmarange** [comment]
Whaouhh impressive this new function!!

**Comment by ddsjoberg** [comment]
> Whaouhh impressive this new function!!

Ahhh! I am excited for it too! Also, it's the last function I have planned for gtsummary, which is also exciting! (Not that we can't add more later! There is still more functionality to add to the existing fns.)

PS Looking forward to `broom.helpers::add_n()`!!

**Comment by larmarange** [comment]
> PS Looking forward to `broom.helpers::add_n()`!!

Should be ready for review this afternoon. ;-)

**Comment by michaelcurry1123** [comment]
It is clear what the difference is when you present means and perform a t-test. However, what does the difference column represent when you perform a Wilcoxon ranked sum test? It is not the difference between the means or medians:

trial %>%
  select(trt, age, marker) %>%
  tbl_summary(by = trt,
              statistic = all_continuous() ~ "{median}",
              digits = all_continuous()~2,
              missing = "no") %>%
  add_difference(test = all_continuous()~"wilcox.test")

**Comment by ddsjoberg** [comment]
> wilcox.test

@michaelcurry1123 
The user will need to look at the documentation for each method to know what is being reported.  In the `?tests` help file we show the code we use: `wilcox.test(variable ~ as.factor(by), data = data, conf.int = TRUE, conf.level = 0.95, ...)`. From there I was leaving it up to the user to investigate what the difference is.

Do you think this should be changed?

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I don't think so but perhaps a note to look to test for documentation on what the difference is? Also when you have a categorial variable in `tbl_summary` and try to run `add_difference()` it throws an error. Was this by design?
```
trial %>%
  select(trt, age, marker,grade) %>%
  tbl_summary(by = trt,
              statistic = all_continuous() ~ "{mean} ({sd})",
              missing = "no") %>%
  add_difference()


```

**Comment by ddsjoberg** [comment]
> @ddsjoberg I don't think so but perhaps a note to look to test for documentation on what the difference is? Also when you have a categorial variable in `tbl_summary` and try to run `add_difference()` it throws an error. Was this by design?
> 
> ```
> trial %>%
>   select(trt, age, marker,grade) %>%
>   tbl_summary(by = trt,
>               statistic = all_continuous() ~ "{mean} ({sd})",
>               missing = "no") %>%
>   add_difference()
> ```

Categorical variables were meant to be excluded...not error! Just updated and it should be ok

**Comment by michaelcurry1123** [comment]
@ddsjoberg  I am not sure how clear the relationship is between `add_p()` and `add_difference()`, when you use `add_p()` with no `add_difference()`  the `difference` column still shows up. Did you want this to happen?

```
trial %>%
  select(trt, age, marker,grade) %>%
  tbl_summary(by = trt) %>%
  add_p()

```

**Comment by michaelcurry1123** [comment]
@ddsjoberg  
if you have categorical variables in tbl_summary a p-value is not calculated if you use `add_difference()` . I tired to use `add_p(include =)` to only get the additional p-value for that variable. However this throws an error, it does not matter if `add_p()` is before or after the `add_difference()`.

```

trial %>%
  select(trt, age, marker,grade) %>%
  tbl_summary(by = trt) %>%
  add_p(include = grade) %>% 
  add_difference()
```

> 
> Error: Column `test_name` not found in `.data`
> Run `rlang::last_error()` to see where the error occurred

**Comment by ddsjoberg** [comment]
> @ddsjoberg I am not sure how clear the relationship is between `add_p()` and `add_difference()`, when you use `add_p()` with no `add_difference()` the `difference` column still shows up. Did you want this to happen?
> 
> ```
> trial %>%
>   select(trt, age, marker,grade) %>%
>   tbl_summary(by = trt) %>%
>   add_p()
> ```

that should def not be happening! Fix pushed!

**Comment by ddsjoberg** [comment]
> @ddsjoberg
> if you have categorical variables in tbl_summary a p-value is not calculated if you use `add_difference()` . I tired to use `add_p(include =)` to only get the additional p-value for that variable. However this throws an error, it does not matter if `add_p()` is before or after the `add_difference()`.
> 
> ```
> 
> trial %>%
>   select(trt, age, marker,grade) %>%
>   tbl_summary(by = trt) %>%
>   add_p(include = grade) %>% 
>   add_difference()
> ```
> 
> > Error: Column `test_name` not found in `.data`
> > Run `rlang::last_error()` to see where the error occurred

In the background, `add_p()` and `add_difference()` are essentially the same function, and as a result cannot both be run. I added an error if a user attempts to do this.

**Pull request merged**
